#!/usr/bin/env python3
"""生成前端炫彩色卡渲染配置(scripts/gen_glass.py)。

输入(均在仓库内,无需解包数据):
  - internal/gamedata/data/COLOR_RANDOM_CONF.ts    39 个配色(ui_color_1/2)
  - internal/gamedata/data/PARTICLE_RANDOM_CONF.ts  4 个粒子(particle_big_icon)
  - internal/gamedata/data/img/dazzling/*.png       底图 Bg/Bg2、粒子大图、隐藏炫彩整图

输出:
  - web/src/data/glassConf.js(前端 import)
      普通炫彩 glass_type=1: value = (粒子id << 20) | 配色id
      隐藏炫彩 glass_type=2: value = HIDDEN_GLASS_CONF.id(1~4 赛季,1000 黑白)

前端渲染(不再预生成色卡 webp,见 web/src/components/badges.jsx):
  普通炫彩用 CSS mask-image 按素材 alpha 蒙版填色合成,与客户端 UMG 一致(docs/data.md 3.5):
    层1 底图 Bg(280x154) 蒙版填 ui_color_2
    层2 中层 Bg2(280x108) 蒙版填 ui_color_1,顶部对齐(同宽)
    层3 顶层 粒子大图(280x154) 蒙版填白
  隐藏炫彩直接引用整图(素材为完整美术图,前端无法重建)。

用法:
  uv run python scripts/gen_glass.py
"""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "internal" / "gamedata" / "data"
DAZZ = DATA / "img" / "dazzling"
OUT = ROOT / "web" / "src" / "data" / "glassConf.js"

# 隐藏炫彩:HIDDEN_GLASS_CONF.id -> 整图资产名(图片按语义重命名过,按前缀匹配)。
# 1/2/3/4 = 第 1~4 赛季炫彩(暗夜拾光/狂欢怪谈/铅字幻梦/月涌狂想),1000 = 黑白。
# 赛季 id 与整图的对应关系来自该条目的 glass_tips_pic 字段,新赛季上线时照此补一行
# (素材是 PetUIStatic 图集里的 PaperSprite,**不是**同名 png,见 scripts/ 下的提取说明)。
HIDDEN_GLASS = {
    1: "img_dazzling_Bg7_png",    # 暗夜拾光(s1赛季炫彩)
    2: "img_dazzling_Bg9_png",    # 狂欢怪谈(s2赛季炫彩)
    3: "img_dazzling_Bg11_png",   # 铅字幻梦(s3赛季炫彩)
    4: "img_dazzling_Bg12_png",   # 月涌狂想(s4赛季炫彩)
    1000: "img_dazzling_Bg8_png",  # 黑白
}

# 普通炫彩底图: Bg 为底(280x154),Bg2 为中层(280x108,顶部对齐,宽度相同)。
BG = "img_dazzling_Bg_png"
BG2 = "img_dazzling_Bg2_png"


def find_png(asset: str) -> Path:
    """按资产名前缀在 dazzling 目录找 png(用户重命名加过语义后缀)。"""
    for f in DAZZ.glob(asset + "*.png"):
        return f
    raise FileNotFoundError(f"dazzling 目录缺 {asset}*.png")


def parse_colors() -> dict:
    """解析 COLOR_RANDOM_CONF.ts:id -> (ui_color_1, ui_color_2) 十六进制(#rrggbb)。"""
    text = (DATA / "COLOR_RANDOM_CONF.ts").read_text(encoding="utf-8")
    colors = {}
    for m in re.finditer(
        r'"id":\s*(\d+).*?"ui_color_1":\s*"#([0-9a-fA-F]{6})".*?"ui_color_2":\s*"#([0-9a-fA-F]{6})"',
        text,
        re.S,
    ):
        colors[int(m.group(1))] = (f"#{m.group(2).lower()}", f"#{m.group(3).lower()}")
    return colors


def parse_particles() -> dict:
    """解析 PARTICLE_RANDOM_CONF.ts:id -> particle_big_icon 资产名(如 img_dazzling_Bg3_png)。"""
    text = (DATA / "PARTICLE_RANDOM_CONF.ts").read_text(encoding="utf-8")
    particles = {}
    for m in re.finditer(
        r'"id":\s*(\d+).*?"particle_big_icon":\s*"[^"]*(img_dazzling_[A-Za-z0-9_]+)[^"]*"',
        text,
        re.S,
    ):
        particles[int(m.group(1))] = m.group(2)
    return particles


def main() -> None:
    colors = parse_colors()
    particles = parse_particles()
    if not colors or not particles:
        raise SystemExit(f"解析 ts 失败:colors={len(colors)} particles={len(particles)}")

    particle_files = {pid: find_png(asset).name for pid, asset in particles.items()}
    hidden_files = {gid: find_png(asset).name for gid, asset in HIDDEN_GLASS.items()}
    bg_file = find_png(BG).name
    bg2_file = find_png(BG2).name

    def js_obj(d: dict) -> str:
        items = ", ".join(f"  {k}: {v}" for k, v in d.items())
        return "{\n" + items + ",\n}"

    body = f"""// Generated by scripts/gen_glass.py — do not edit directly.
// 前端炫彩色卡渲染配置:色卡由前端按素材 alpha 蒙版填色合成(见 web/src/components/badges.jsx)。
// 普通炫彩 value = (粒子id << 20) | 配色id;隐藏炫彩 value 见 GLASS_HIDDEN(1~4 赛季,1000 黑白)。
export const GLASS_BG = '{bg_file}'
export const GLASS_BG2 = '{bg2_file}'
// 粒子 id -> 粒子大图文件名(PARTICLE_RANDOM_CONF.particle_big_icon)
export const GLASS_PARTICLES = {js_obj({k: f"'{v}'" for k, v in particle_files.items()})}
// 配色 id -> [ui_color_1, ui_color_2]
export const GLASS_COLORS = {js_obj({k: f"['{v[0]}', '{v[1]}']" for k, v in colors.items()})}
// 隐藏炫彩 value -> 整图文件名(HIDDEN_GLASS_CONF.id)
export const GLASS_HIDDEN = {js_obj({k: f"'{v}'" for k, v in hidden_files.items()})}
"""
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(body, encoding="utf-8")
    print(f"已生成 {OUT} (配色 {len(colors)}、粒子 {len(particles)}、隐藏 {len(hidden_files)})")


if __name__ == "__main__":
    main()
