// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: com_pet_team.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PetSkillEquipInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *uint32                `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Pos           *uint32                `protobuf:"varint,2,opt,name=pos" json:"pos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetSkillEquipInfo) Reset() {
	*x = PetSkillEquipInfo{}
	mi := &file_com_pet_team_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetSkillEquipInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetSkillEquipInfo) ProtoMessage() {}

func (x *PetSkillEquipInfo) ProtoReflect() protoreflect.Message {
	mi := &file_com_pet_team_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetSkillEquipInfo.ProtoReflect.Descriptor instead.
func (*PetSkillEquipInfo) Descriptor() ([]byte, []int) {
	return file_com_pet_team_proto_rawDescGZIP(), []int{0}
}

func (x *PetSkillEquipInfo) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *PetSkillEquipInfo) GetPos() uint32 {
	if x != nil && x.Pos != nil {
		return *x.Pos
	}
	return 0
}

type PetTeam_PetInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PetGid        *uint32                `protobuf:"varint,1,opt,name=pet_gid,json=petGid" json:"pet_gid,omitempty"`
	EquipInfos    []*PetSkillEquipInfo   `protobuf:"bytes,2,rep,name=equip_infos,json=equipInfos" json:"equip_infos,omitempty"`
	IsTrialPet    *bool                  `protobuf:"varint,3,opt,name=is_trial_pet,json=isTrialPet" json:"is_trial_pet,omitempty"`
	Type          *PetTypeInfo           `protobuf:"bytes,4,opt,name=type" json:"type,omitempty"`
	RawPetGid     *uint32                `protobuf:"varint,5,opt,name=raw_pet_gid,json=rawPetGid" json:"raw_pet_gid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetTeam_PetInfo) Reset() {
	*x = PetTeam_PetInfo{}
	mi := &file_com_pet_team_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetTeam_PetInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetTeam_PetInfo) ProtoMessage() {}

func (x *PetTeam_PetInfo) ProtoReflect() protoreflect.Message {
	mi := &file_com_pet_team_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetTeam_PetInfo.ProtoReflect.Descriptor instead.
func (*PetTeam_PetInfo) Descriptor() ([]byte, []int) {
	return file_com_pet_team_proto_rawDescGZIP(), []int{1}
}

func (x *PetTeam_PetInfo) GetPetGid() uint32 {
	if x != nil && x.PetGid != nil {
		return *x.PetGid
	}
	return 0
}

func (x *PetTeam_PetInfo) GetEquipInfos() []*PetSkillEquipInfo {
	if x != nil {
		return x.EquipInfos
	}
	return nil
}

func (x *PetTeam_PetInfo) GetIsTrialPet() bool {
	if x != nil && x.IsTrialPet != nil {
		return *x.IsTrialPet
	}
	return false
}

func (x *PetTeam_PetInfo) GetType() *PetTypeInfo {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *PetTeam_PetInfo) GetRawPetGid() uint32 {
	if x != nil && x.RawPetGid != nil {
		return *x.RawPetGid
	}
	return 0
}

type PetTeam struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	PetInfos                     []*PetTeam_PetInfo     `protobuf:"bytes,2,rep,name=pet_infos,json=petInfos" json:"pet_infos,omitempty"`
	TeamName                     *string                `protobuf:"bytes,3,opt,name=team_name,json=teamName" json:"team_name,omitempty"`
	RoleMagicGid                 *uint32                `protobuf:"varint,4,opt,name=role_magic_gid,json=roleMagicGid" json:"role_magic_gid,omitempty"`
	TrialPet                     *TrialPetBrief         `protobuf:"bytes,5,opt,name=trial_pet,json=trialPet" json:"trial_pet,omitempty"`
	IsMirror                     *bool                  `protobuf:"varint,6,opt,name=is_mirror,json=isMirror" json:"is_mirror,omitempty"`
	MirrorFriendName             *string                `protobuf:"bytes,7,opt,name=mirror_friend_name,json=mirrorFriendName" json:"mirror_friend_name,omitempty"`
	TeamIdx                      *uint32                `protobuf:"varint,8,opt,name=team_idx,json=teamIdx" json:"team_idx,omitempty"`
	MirrorFriendUin              *uint32                `protobuf:"varint,9,opt,name=mirror_friend_uin,json=mirrorFriendUin" json:"mirror_friend_uin,omitempty"`
	MirrorFriendCardIconSelected *uint32                `protobuf:"varint,10,opt,name=mirror_friend_card_icon_selected,json=mirrorFriendCardIconSelected" json:"mirror_friend_card_icon_selected,omitempty"`
	MirrorMagicId                *uint32                `protobuf:"varint,11,opt,name=mirror_magic_id,json=mirrorMagicId" json:"mirror_magic_id,omitempty"`
	MirrorBossEvoItems           []uint32               `protobuf:"varint,12,rep,name=mirror_boss_evo_items,json=mirrorBossEvoItems" json:"mirror_boss_evo_items,omitempty"`
	MirrorCopyTs                 *uint32                `protobuf:"varint,13,opt,name=mirror_copy_ts,json=mirrorCopyTs" json:"mirror_copy_ts,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *PetTeam) Reset() {
	*x = PetTeam{}
	mi := &file_com_pet_team_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetTeam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetTeam) ProtoMessage() {}

func (x *PetTeam) ProtoReflect() protoreflect.Message {
	mi := &file_com_pet_team_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetTeam.ProtoReflect.Descriptor instead.
func (*PetTeam) Descriptor() ([]byte, []int) {
	return file_com_pet_team_proto_rawDescGZIP(), []int{2}
}

func (x *PetTeam) GetPetInfos() []*PetTeam_PetInfo {
	if x != nil {
		return x.PetInfos
	}
	return nil
}

func (x *PetTeam) GetTeamName() string {
	if x != nil && x.TeamName != nil {
		return *x.TeamName
	}
	return ""
}

func (x *PetTeam) GetRoleMagicGid() uint32 {
	if x != nil && x.RoleMagicGid != nil {
		return *x.RoleMagicGid
	}
	return 0
}

func (x *PetTeam) GetTrialPet() *TrialPetBrief {
	if x != nil {
		return x.TrialPet
	}
	return nil
}

func (x *PetTeam) GetIsMirror() bool {
	if x != nil && x.IsMirror != nil {
		return *x.IsMirror
	}
	return false
}

func (x *PetTeam) GetMirrorFriendName() string {
	if x != nil && x.MirrorFriendName != nil {
		return *x.MirrorFriendName
	}
	return ""
}

func (x *PetTeam) GetTeamIdx() uint32 {
	if x != nil && x.TeamIdx != nil {
		return *x.TeamIdx
	}
	return 0
}

func (x *PetTeam) GetMirrorFriendUin() uint32 {
	if x != nil && x.MirrorFriendUin != nil {
		return *x.MirrorFriendUin
	}
	return 0
}

func (x *PetTeam) GetMirrorFriendCardIconSelected() uint32 {
	if x != nil && x.MirrorFriendCardIconSelected != nil {
		return *x.MirrorFriendCardIconSelected
	}
	return 0
}

func (x *PetTeam) GetMirrorMagicId() uint32 {
	if x != nil && x.MirrorMagicId != nil {
		return *x.MirrorMagicId
	}
	return 0
}

func (x *PetTeam) GetMirrorBossEvoItems() []uint32 {
	if x != nil {
		return x.MirrorBossEvoItems
	}
	return nil
}

func (x *PetTeam) GetMirrorCopyTs() uint32 {
	if x != nil && x.MirrorCopyTs != nil {
		return *x.MirrorCopyTs
	}
	return 0
}

type PetSynchronInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *uint32                `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	Number        *uint32                `protobuf:"varint,2,opt,name=number" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetSynchronInfo) Reset() {
	*x = PetSynchronInfo{}
	mi := &file_com_pet_team_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetSynchronInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetSynchronInfo) ProtoMessage() {}

func (x *PetSynchronInfo) ProtoReflect() protoreflect.Message {
	mi := &file_com_pet_team_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetSynchronInfo.ProtoReflect.Descriptor instead.
func (*PetSynchronInfo) Descriptor() ([]byte, []int) {
	return file_com_pet_team_proto_rawDescGZIP(), []int{3}
}

func (x *PetSynchronInfo) GetType() uint32 {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return 0
}

func (x *PetSynchronInfo) GetNumber() uint32 {
	if x != nil && x.Number != nil {
		return *x.Number
	}
	return 0
}

type PetTeamInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MainTeamIdx   *uint32                `protobuf:"varint,1,opt,name=main_team_idx,json=mainTeamIdx" json:"main_team_idx,omitempty"`
	Teams         []*PetTeam             `protobuf:"bytes,2,rep,name=teams" json:"teams,omitempty"`
	Synchron      []*PetSynchronInfo     `protobuf:"bytes,3,rep,name=synchron" json:"synchron,omitempty"`
	TeamType      *uint32                `protobuf:"varint,4,opt,name=team_type,json=teamType" json:"team_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetTeamInfo) Reset() {
	*x = PetTeamInfo{}
	mi := &file_com_pet_team_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetTeamInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetTeamInfo) ProtoMessage() {}

func (x *PetTeamInfo) ProtoReflect() protoreflect.Message {
	mi := &file_com_pet_team_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetTeamInfo.ProtoReflect.Descriptor instead.
func (*PetTeamInfo) Descriptor() ([]byte, []int) {
	return file_com_pet_team_proto_rawDescGZIP(), []int{4}
}

func (x *PetTeamInfo) GetMainTeamIdx() uint32 {
	if x != nil && x.MainTeamIdx != nil {
		return *x.MainTeamIdx
	}
	return 0
}

func (x *PetTeamInfo) GetTeams() []*PetTeam {
	if x != nil {
		return x.Teams
	}
	return nil
}

func (x *PetTeamInfo) GetSynchron() []*PetSynchronInfo {
	if x != nil {
		return x.Synchron
	}
	return nil
}

func (x *PetTeamInfo) GetTeamType() uint32 {
	if x != nil && x.TeamType != nil {
		return *x.TeamType
	}
	return 0
}

type SharedPetTeamInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamName      *string                `protobuf:"bytes,1,opt,name=team_name,json=teamName" json:"team_name,omitempty"`
	TeamType      *uint32                `protobuf:"varint,2,opt,name=team_type,json=teamType" json:"team_type,omitempty"`
	RoleMagicId   *uint32                `protobuf:"varint,3,opt,name=role_magic_id,json=roleMagicId" json:"role_magic_id,omitempty"`
	Pets          []*SharedPetInfo       `protobuf:"bytes,4,rep,name=pets" json:"pets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SharedPetTeamInfo) Reset() {
	*x = SharedPetTeamInfo{}
	mi := &file_com_pet_team_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SharedPetTeamInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SharedPetTeamInfo) ProtoMessage() {}

func (x *SharedPetTeamInfo) ProtoReflect() protoreflect.Message {
	mi := &file_com_pet_team_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SharedPetTeamInfo.ProtoReflect.Descriptor instead.
func (*SharedPetTeamInfo) Descriptor() ([]byte, []int) {
	return file_com_pet_team_proto_rawDescGZIP(), []int{5}
}

func (x *SharedPetTeamInfo) GetTeamName() string {
	if x != nil && x.TeamName != nil {
		return *x.TeamName
	}
	return ""
}

func (x *SharedPetTeamInfo) GetTeamType() uint32 {
	if x != nil && x.TeamType != nil {
		return *x.TeamType
	}
	return 0
}

func (x *SharedPetTeamInfo) GetRoleMagicId() uint32 {
	if x != nil && x.RoleMagicId != nil {
		return *x.RoleMagicId
	}
	return 0
}

func (x *SharedPetTeamInfo) GetPets() []*SharedPetInfo {
	if x != nil {
		return x.Pets
	}
	return nil
}

type SharedPetInfo struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	HpTalent                 *int32                 `protobuf:"varint,1,opt,name=hp_talent,json=hpTalent" json:"hp_talent,omitempty"`
	AttackTalent             *int32                 `protobuf:"varint,2,opt,name=attack_talent,json=attackTalent" json:"attack_talent,omitempty"`
	SpecialAttackTalent      *int32                 `protobuf:"varint,3,opt,name=special_attack_talent,json=specialAttackTalent" json:"special_attack_talent,omitempty"`
	DefenseTalent            *int32                 `protobuf:"varint,4,opt,name=defense_talent,json=defenseTalent" json:"defense_talent,omitempty"`
	SpecialDefenseTalent     *int32                 `protobuf:"varint,5,opt,name=special_defense_talent,json=specialDefenseTalent" json:"special_defense_talent,omitempty"`
	SpeedTalent              *int32                 `protobuf:"varint,6,opt,name=speed_talent,json=speedTalent" json:"speed_talent,omitempty"`
	BaseConfId               *uint32                `protobuf:"varint,7,opt,name=base_conf_id,json=baseConfId" json:"base_conf_id,omitempty"`
	Nature                   *uint32                `protobuf:"varint,8,opt,name=nature" json:"nature,omitempty"`
	BloodId                  *uint32                `protobuf:"varint,9,opt,name=blood_id,json=bloodId" json:"blood_id,omitempty"`
	Skills                   []*PetSkillEquipInfo   `protobuf:"bytes,10,rep,name=skills" json:"skills,omitempty"`
	ChangedNaturePosAttrType *uint32                `protobuf:"varint,11,opt,name=changed_nature_pos_attr_type,json=changedNaturePosAttrType" json:"changed_nature_pos_attr_type,omitempty"`
	ChangedNatureNegAttrType *uint32                `protobuf:"varint,12,opt,name=changed_nature_neg_attr_type,json=changedNatureNegAttrType" json:"changed_nature_neg_attr_type,omitempty"`
	Gid                      *uint64                `protobuf:"varint,13,opt,name=gid" json:"gid,omitempty"`
	Type                     *PetTypeInfo           `protobuf:"bytes,14,opt,name=type" json:"type,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *SharedPetInfo) Reset() {
	*x = SharedPetInfo{}
	mi := &file_com_pet_team_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SharedPetInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SharedPetInfo) ProtoMessage() {}

func (x *SharedPetInfo) ProtoReflect() protoreflect.Message {
	mi := &file_com_pet_team_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SharedPetInfo.ProtoReflect.Descriptor instead.
func (*SharedPetInfo) Descriptor() ([]byte, []int) {
	return file_com_pet_team_proto_rawDescGZIP(), []int{6}
}

func (x *SharedPetInfo) GetHpTalent() int32 {
	if x != nil && x.HpTalent != nil {
		return *x.HpTalent
	}
	return 0
}

func (x *SharedPetInfo) GetAttackTalent() int32 {
	if x != nil && x.AttackTalent != nil {
		return *x.AttackTalent
	}
	return 0
}

func (x *SharedPetInfo) GetSpecialAttackTalent() int32 {
	if x != nil && x.SpecialAttackTalent != nil {
		return *x.SpecialAttackTalent
	}
	return 0
}

func (x *SharedPetInfo) GetDefenseTalent() int32 {
	if x != nil && x.DefenseTalent != nil {
		return *x.DefenseTalent
	}
	return 0
}

func (x *SharedPetInfo) GetSpecialDefenseTalent() int32 {
	if x != nil && x.SpecialDefenseTalent != nil {
		return *x.SpecialDefenseTalent
	}
	return 0
}

func (x *SharedPetInfo) GetSpeedTalent() int32 {
	if x != nil && x.SpeedTalent != nil {
		return *x.SpeedTalent
	}
	return 0
}

func (x *SharedPetInfo) GetBaseConfId() uint32 {
	if x != nil && x.BaseConfId != nil {
		return *x.BaseConfId
	}
	return 0
}

func (x *SharedPetInfo) GetNature() uint32 {
	if x != nil && x.Nature != nil {
		return *x.Nature
	}
	return 0
}

func (x *SharedPetInfo) GetBloodId() uint32 {
	if x != nil && x.BloodId != nil {
		return *x.BloodId
	}
	return 0
}

func (x *SharedPetInfo) GetSkills() []*PetSkillEquipInfo {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *SharedPetInfo) GetChangedNaturePosAttrType() uint32 {
	if x != nil && x.ChangedNaturePosAttrType != nil {
		return *x.ChangedNaturePosAttrType
	}
	return 0
}

func (x *SharedPetInfo) GetChangedNatureNegAttrType() uint32 {
	if x != nil && x.ChangedNatureNegAttrType != nil {
		return *x.ChangedNatureNegAttrType
	}
	return 0
}

func (x *SharedPetInfo) GetGid() uint64 {
	if x != nil && x.Gid != nil {
		return *x.Gid
	}
	return 0
}

func (x *SharedPetInfo) GetType() *PetTypeInfo {
	if x != nil {
		return x.Type
	}
	return nil
}

type AdjustedPetTeamInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pets          []*AdjustedPet         `protobuf:"bytes,1,rep,name=pets" json:"pets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdjustedPetTeamInfo) Reset() {
	*x = AdjustedPetTeamInfo{}
	mi := &file_com_pet_team_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdjustedPetTeamInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdjustedPetTeamInfo) ProtoMessage() {}

func (x *AdjustedPetTeamInfo) ProtoReflect() protoreflect.Message {
	mi := &file_com_pet_team_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdjustedPetTeamInfo.ProtoReflect.Descriptor instead.
func (*AdjustedPetTeamInfo) Descriptor() ([]byte, []int) {
	return file_com_pet_team_proto_rawDescGZIP(), []int{7}
}

func (x *AdjustedPetTeamInfo) GetPets() []*AdjustedPet {
	if x != nil {
		return x.Pets
	}
	return nil
}

type AdjustedPet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gid           *uint32                `protobuf:"varint,1,opt,name=gid" json:"gid,omitempty"`
	Skills        []*AdjustedPetSkill    `protobuf:"bytes,2,rep,name=skills" json:"skills,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdjustedPet) Reset() {
	*x = AdjustedPet{}
	mi := &file_com_pet_team_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdjustedPet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdjustedPet) ProtoMessage() {}

func (x *AdjustedPet) ProtoReflect() protoreflect.Message {
	mi := &file_com_pet_team_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdjustedPet.ProtoReflect.Descriptor instead.
func (*AdjustedPet) Descriptor() ([]byte, []int) {
	return file_com_pet_team_proto_rawDescGZIP(), []int{8}
}

func (x *AdjustedPet) GetGid() uint32 {
	if x != nil && x.Gid != nil {
		return *x.Gid
	}
	return 0
}

func (x *AdjustedPet) GetSkills() []*AdjustedPetSkill {
	if x != nil {
		return x.Skills
	}
	return nil
}

type AdjustedPetSkill struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                *uint32                `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Pos               *uint32                `protobuf:"varint,2,opt,name=pos" json:"pos,omitempty"`
	AlternativeSkills []uint32               `protobuf:"varint,3,rep,name=alternative_skills,json=alternativeSkills" json:"alternative_skills,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AdjustedPetSkill) Reset() {
	*x = AdjustedPetSkill{}
	mi := &file_com_pet_team_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdjustedPetSkill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdjustedPetSkill) ProtoMessage() {}

func (x *AdjustedPetSkill) ProtoReflect() protoreflect.Message {
	mi := &file_com_pet_team_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdjustedPetSkill.ProtoReflect.Descriptor instead.
func (*AdjustedPetSkill) Descriptor() ([]byte, []int) {
	return file_com_pet_team_proto_rawDescGZIP(), []int{9}
}

func (x *AdjustedPetSkill) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *AdjustedPetSkill) GetPos() uint32 {
	if x != nil && x.Pos != nil {
		return *x.Pos
	}
	return 0
}

func (x *AdjustedPetSkill) GetAlternativeSkills() []uint32 {
	if x != nil {
		return x.AlternativeSkills
	}
	return nil
}

type RecommendPetTeamInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PetTeamInfo    *SharedPetTeamInfo     `protobuf:"bytes,1,opt,name=pet_team_info,json=petTeamInfo" json:"pet_team_info,omitempty"`
	PetTeamShareId *string                `protobuf:"bytes,2,opt,name=pet_team_share_id,json=petTeamShareId" json:"pet_team_share_id,omitempty"`
	PlayerName     *string                `protobuf:"bytes,3,opt,name=player_name,json=playerName" json:"player_name,omitempty"`
	PlayerHeadpic  *string                `protobuf:"bytes,4,opt,name=player_headpic,json=playerHeadpic" json:"player_headpic,omitempty"`
	PetLevel       *uint32                `protobuf:"varint,5,opt,name=pet_level,json=petLevel" json:"pet_level,omitempty"`
	TeamName       *string                `protobuf:"bytes,6,opt,name=team_name,json=teamName" json:"team_name,omitempty"`
	TeamId         *uint32                `protobuf:"varint,7,opt,name=team_id,json=teamId" json:"team_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RecommendPetTeamInfo) Reset() {
	*x = RecommendPetTeamInfo{}
	mi := &file_com_pet_team_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendPetTeamInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendPetTeamInfo) ProtoMessage() {}

func (x *RecommendPetTeamInfo) ProtoReflect() protoreflect.Message {
	mi := &file_com_pet_team_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendPetTeamInfo.ProtoReflect.Descriptor instead.
func (*RecommendPetTeamInfo) Descriptor() ([]byte, []int) {
	return file_com_pet_team_proto_rawDescGZIP(), []int{10}
}

func (x *RecommendPetTeamInfo) GetPetTeamInfo() *SharedPetTeamInfo {
	if x != nil {
		return x.PetTeamInfo
	}
	return nil
}

func (x *RecommendPetTeamInfo) GetPetTeamShareId() string {
	if x != nil && x.PetTeamShareId != nil {
		return *x.PetTeamShareId
	}
	return ""
}

func (x *RecommendPetTeamInfo) GetPlayerName() string {
	if x != nil && x.PlayerName != nil {
		return *x.PlayerName
	}
	return ""
}

func (x *RecommendPetTeamInfo) GetPlayerHeadpic() string {
	if x != nil && x.PlayerHeadpic != nil {
		return *x.PlayerHeadpic
	}
	return ""
}

func (x *RecommendPetTeamInfo) GetPetLevel() uint32 {
	if x != nil && x.PetLevel != nil {
		return *x.PetLevel
	}
	return 0
}

func (x *RecommendPetTeamInfo) GetTeamName() string {
	if x != nil && x.TeamName != nil {
		return *x.TeamName
	}
	return ""
}

func (x *RecommendPetTeamInfo) GetTeamId() uint32 {
	if x != nil && x.TeamId != nil {
		return *x.TeamId
	}
	return 0
}

type FriendPetTeamInfo struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Pets                   []*PetData             `protobuf:"bytes,1,rep,name=pets" json:"pets,omitempty"`
	Teams                  []*PetTeam             `protobuf:"bytes,2,rep,name=teams" json:"teams,omitempty"`
	FriendName             *string                `protobuf:"bytes,3,opt,name=friend_name,json=friendName" json:"friend_name,omitempty"`
	FriendUin              *uint32                `protobuf:"varint,4,opt,name=friend_uin,json=friendUin" json:"friend_uin,omitempty"`
	FriendLevel            *uint32                `protobuf:"varint,5,opt,name=friend_level,json=friendLevel" json:"friend_level,omitempty"`
	FriendCardIconSelected *uint32                `protobuf:"varint,6,opt,name=friend_card_icon_selected,json=friendCardIconSelected" json:"friend_card_icon_selected,omitempty"`
	FriendIsMirrorUnlocked *bool                  `protobuf:"varint,7,opt,name=friend_is_mirror_unlocked,json=friendIsMirrorUnlocked" json:"friend_is_mirror_unlocked,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *FriendPetTeamInfo) Reset() {
	*x = FriendPetTeamInfo{}
	mi := &file_com_pet_team_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendPetTeamInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendPetTeamInfo) ProtoMessage() {}

func (x *FriendPetTeamInfo) ProtoReflect() protoreflect.Message {
	mi := &file_com_pet_team_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendPetTeamInfo.ProtoReflect.Descriptor instead.
func (*FriendPetTeamInfo) Descriptor() ([]byte, []int) {
	return file_com_pet_team_proto_rawDescGZIP(), []int{11}
}

func (x *FriendPetTeamInfo) GetPets() []*PetData {
	if x != nil {
		return x.Pets
	}
	return nil
}

func (x *FriendPetTeamInfo) GetTeams() []*PetTeam {
	if x != nil {
		return x.Teams
	}
	return nil
}

func (x *FriendPetTeamInfo) GetFriendName() string {
	if x != nil && x.FriendName != nil {
		return *x.FriendName
	}
	return ""
}

func (x *FriendPetTeamInfo) GetFriendUin() uint32 {
	if x != nil && x.FriendUin != nil {
		return *x.FriendUin
	}
	return 0
}

func (x *FriendPetTeamInfo) GetFriendLevel() uint32 {
	if x != nil && x.FriendLevel != nil {
		return *x.FriendLevel
	}
	return 0
}

func (x *FriendPetTeamInfo) GetFriendCardIconSelected() uint32 {
	if x != nil && x.FriendCardIconSelected != nil {
		return *x.FriendCardIconSelected
	}
	return 0
}

func (x *FriendPetTeamInfo) GetFriendIsMirrorUnlocked() bool {
	if x != nil && x.FriendIsMirrorUnlocked != nil {
		return *x.FriendIsMirrorUnlocked
	}
	return false
}

type FriendPetTeamIndex struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IndexString   *string                `protobuf:"bytes,1,opt,name=index_string,json=indexString" json:"index_string,omitempty"`
	ShareBanUntil *uint32                `protobuf:"varint,3,opt,name=share_ban_until,json=shareBanUntil" json:"share_ban_until,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendPetTeamIndex) Reset() {
	*x = FriendPetTeamIndex{}
	mi := &file_com_pet_team_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendPetTeamIndex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendPetTeamIndex) ProtoMessage() {}

func (x *FriendPetTeamIndex) ProtoReflect() protoreflect.Message {
	mi := &file_com_pet_team_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendPetTeamIndex.ProtoReflect.Descriptor instead.
func (*FriendPetTeamIndex) Descriptor() ([]byte, []int) {
	return file_com_pet_team_proto_rawDescGZIP(), []int{12}
}

func (x *FriendPetTeamIndex) GetIndexString() string {
	if x != nil && x.IndexString != nil {
		return *x.IndexString
	}
	return ""
}

func (x *FriendPetTeamIndex) GetShareBanUntil() uint32 {
	if x != nil && x.ShareBanUntil != nil {
		return *x.ShareBanUntil
	}
	return 0
}

type FriendPetTeamBufferFriendInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             []byte                 `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Level            *uint32                `protobuf:"varint,2,opt,name=level" json:"level,omitempty"`
	CardIconSelected *uint32                `protobuf:"varint,3,opt,name=card_icon_selected,json=cardIconSelected" json:"card_icon_selected,omitempty"`
	Note             []byte                 `protobuf:"bytes,4,opt,name=note" json:"note,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FriendPetTeamBufferFriendInfo) Reset() {
	*x = FriendPetTeamBufferFriendInfo{}
	mi := &file_com_pet_team_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendPetTeamBufferFriendInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendPetTeamBufferFriendInfo) ProtoMessage() {}

func (x *FriendPetTeamBufferFriendInfo) ProtoReflect() protoreflect.Message {
	mi := &file_com_pet_team_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendPetTeamBufferFriendInfo.ProtoReflect.Descriptor instead.
func (*FriendPetTeamBufferFriendInfo) Descriptor() ([]byte, []int) {
	return file_com_pet_team_proto_rawDescGZIP(), []int{13}
}

func (x *FriendPetTeamBufferFriendInfo) GetName() []byte {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *FriendPetTeamBufferFriendInfo) GetLevel() uint32 {
	if x != nil && x.Level != nil {
		return *x.Level
	}
	return 0
}

func (x *FriendPetTeamBufferFriendInfo) GetCardIconSelected() uint32 {
	if x != nil && x.CardIconSelected != nil {
		return *x.CardIconSelected
	}
	return 0
}

func (x *FriendPetTeamBufferFriendInfo) GetNote() []byte {
	if x != nil {
		return x.Note
	}
	return nil
}

var File_com_pet_team_proto protoreflect.FileDescriptor

const file_com_pet_team_proto_rawDesc = "" +
	"\n" +
	"\x12com_pet_team.proto\x12\x04Next\x1a\rcom_pet.proto\"5\n" +
	"\x11PetSkillEquipInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x10\n" +
	"\x03pos\x18\x02 \x01(\rR\x03pos\"\xcd\x01\n" +
	"\x0fPetTeam_PetInfo\x12\x17\n" +
	"\apet_gid\x18\x01 \x01(\rR\x06petGid\x128\n" +
	"\vequip_infos\x18\x02 \x03(\v2\x17.Next.PetSkillEquipInfoR\n" +
	"equipInfos\x12 \n" +
	"\fis_trial_pet\x18\x03 \x01(\bR\n" +
	"isTrialPet\x12%\n" +
	"\x04type\x18\x04 \x01(\v2\x11.Next.PetTypeInfoR\x04type\x12\x1e\n" +
	"\vraw_pet_gid\x18\x05 \x01(\rR\trawPetGid\"\x8d\x04\n" +
	"\aPetTeam\x122\n" +
	"\tpet_infos\x18\x02 \x03(\v2\x15.Next.PetTeam_PetInfoR\bpetInfos\x12\x1b\n" +
	"\tteam_name\x18\x03 \x01(\tR\bteamName\x12$\n" +
	"\x0erole_magic_gid\x18\x04 \x01(\rR\froleMagicGid\x120\n" +
	"\ttrial_pet\x18\x05 \x01(\v2\x13.Next.TrialPetBriefR\btrialPet\x12\x1b\n" +
	"\tis_mirror\x18\x06 \x01(\bR\bisMirror\x12,\n" +
	"\x12mirror_friend_name\x18\a \x01(\tR\x10mirrorFriendName\x12\x19\n" +
	"\bteam_idx\x18\b \x01(\rR\ateamIdx\x12*\n" +
	"\x11mirror_friend_uin\x18\t \x01(\rR\x0fmirrorFriendUin\x12F\n" +
	" mirror_friend_card_icon_selected\x18\n" +
	" \x01(\rR\x1cmirrorFriendCardIconSelected\x12&\n" +
	"\x0fmirror_magic_id\x18\v \x01(\rR\rmirrorMagicId\x121\n" +
	"\x15mirror_boss_evo_items\x18\f \x03(\rR\x12mirrorBossEvoItems\x12$\n" +
	"\x0emirror_copy_ts\x18\r \x01(\rR\fmirrorCopyTs\"=\n" +
	"\x0fPetSynchronInfo\x12\x12\n" +
	"\x04type\x18\x01 \x01(\rR\x04type\x12\x16\n" +
	"\x06number\x18\x02 \x01(\rR\x06number\"\xa6\x01\n" +
	"\vPetTeamInfo\x12\"\n" +
	"\rmain_team_idx\x18\x01 \x01(\rR\vmainTeamIdx\x12#\n" +
	"\x05teams\x18\x02 \x03(\v2\r.Next.PetTeamR\x05teams\x121\n" +
	"\bsynchron\x18\x03 \x03(\v2\x15.Next.PetSynchronInfoR\bsynchron\x12\x1b\n" +
	"\tteam_type\x18\x04 \x01(\rR\bteamType\"\x9a\x01\n" +
	"\x11SharedPetTeamInfo\x12\x1b\n" +
	"\tteam_name\x18\x01 \x01(\tR\bteamName\x12\x1b\n" +
	"\tteam_type\x18\x02 \x01(\rR\bteamType\x12\"\n" +
	"\rrole_magic_id\x18\x03 \x01(\rR\vroleMagicId\x12'\n" +
	"\x04pets\x18\x04 \x03(\v2\x13.Next.SharedPetInfoR\x04pets\"\xc4\x04\n" +
	"\rSharedPetInfo\x12\x1b\n" +
	"\thp_talent\x18\x01 \x01(\x05R\bhpTalent\x12#\n" +
	"\rattack_talent\x18\x02 \x01(\x05R\fattackTalent\x122\n" +
	"\x15special_attack_talent\x18\x03 \x01(\x05R\x13specialAttackTalent\x12%\n" +
	"\x0edefense_talent\x18\x04 \x01(\x05R\rdefenseTalent\x124\n" +
	"\x16special_defense_talent\x18\x05 \x01(\x05R\x14specialDefenseTalent\x12!\n" +
	"\fspeed_talent\x18\x06 \x01(\x05R\vspeedTalent\x12 \n" +
	"\fbase_conf_id\x18\a \x01(\rR\n" +
	"baseConfId\x12\x16\n" +
	"\x06nature\x18\b \x01(\rR\x06nature\x12\x19\n" +
	"\bblood_id\x18\t \x01(\rR\abloodId\x12/\n" +
	"\x06skills\x18\n" +
	" \x03(\v2\x17.Next.PetSkillEquipInfoR\x06skills\x12>\n" +
	"\x1cchanged_nature_pos_attr_type\x18\v \x01(\rR\x18changedNaturePosAttrType\x12>\n" +
	"\x1cchanged_nature_neg_attr_type\x18\f \x01(\rR\x18changedNatureNegAttrType\x12\x10\n" +
	"\x03gid\x18\r \x01(\x04R\x03gid\x12%\n" +
	"\x04type\x18\x0e \x01(\v2\x11.Next.PetTypeInfoR\x04type\"<\n" +
	"\x13AdjustedPetTeamInfo\x12%\n" +
	"\x04pets\x18\x01 \x03(\v2\x11.Next.AdjustedPetR\x04pets\"O\n" +
	"\vAdjustedPet\x12\x10\n" +
	"\x03gid\x18\x01 \x01(\rR\x03gid\x12.\n" +
	"\x06skills\x18\x02 \x03(\v2\x16.Next.AdjustedPetSkillR\x06skills\"c\n" +
	"\x10AdjustedPetSkill\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x10\n" +
	"\x03pos\x18\x02 \x01(\rR\x03pos\x12-\n" +
	"\x12alternative_skills\x18\x03 \x03(\rR\x11alternativeSkills\"\x99\x02\n" +
	"\x14RecommendPetTeamInfo\x12;\n" +
	"\rpet_team_info\x18\x01 \x01(\v2\x17.Next.SharedPetTeamInfoR\vpetTeamInfo\x12)\n" +
	"\x11pet_team_share_id\x18\x02 \x01(\tR\x0epetTeamShareId\x12\x1f\n" +
	"\vplayer_name\x18\x03 \x01(\tR\n" +
	"playerName\x12%\n" +
	"\x0eplayer_headpic\x18\x04 \x01(\tR\rplayerHeadpic\x12\x1b\n" +
	"\tpet_level\x18\x05 \x01(\rR\bpetLevel\x12\x1b\n" +
	"\tteam_name\x18\x06 \x01(\tR\bteamName\x12\x17\n" +
	"\ateam_id\x18\a \x01(\rR\x06teamId\"\xb4\x02\n" +
	"\x11FriendPetTeamInfo\x12!\n" +
	"\x04pets\x18\x01 \x03(\v2\r.Next.PetDataR\x04pets\x12#\n" +
	"\x05teams\x18\x02 \x03(\v2\r.Next.PetTeamR\x05teams\x12\x1f\n" +
	"\vfriend_name\x18\x03 \x01(\tR\n" +
	"friendName\x12\x1d\n" +
	"\n" +
	"friend_uin\x18\x04 \x01(\rR\tfriendUin\x12!\n" +
	"\ffriend_level\x18\x05 \x01(\rR\vfriendLevel\x129\n" +
	"\x19friend_card_icon_selected\x18\x06 \x01(\rR\x16friendCardIconSelected\x129\n" +
	"\x19friend_is_mirror_unlocked\x18\a \x01(\bR\x16friendIsMirrorUnlocked\"_\n" +
	"\x12FriendPetTeamIndex\x12!\n" +
	"\findex_string\x18\x01 \x01(\tR\vindexString\x12&\n" +
	"\x0fshare_ban_until\x18\x03 \x01(\rR\rshareBanUntil\"\x8b\x01\n" +
	"\x1dFriendPetTeamBufferFriendInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\fR\x04name\x12\x14\n" +
	"\x05level\x18\x02 \x01(\rR\x05level\x12,\n" +
	"\x12card_icon_selected\x18\x03 \x01(\rR\x10cardIconSelected\x12\x12\n" +
	"\x04note\x18\x04 \x01(\fR\x04note"

var (
	file_com_pet_team_proto_rawDescOnce sync.Once
	file_com_pet_team_proto_rawDescData []byte
)

func file_com_pet_team_proto_rawDescGZIP() []byte {
	file_com_pet_team_proto_rawDescOnce.Do(func() {
		file_com_pet_team_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_com_pet_team_proto_rawDesc), len(file_com_pet_team_proto_rawDesc)))
	})
	return file_com_pet_team_proto_rawDescData
}

var file_com_pet_team_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_com_pet_team_proto_goTypes = []any{
	(*PetSkillEquipInfo)(nil),             // 0: Next.PetSkillEquipInfo
	(*PetTeam_PetInfo)(nil),               // 1: Next.PetTeam_PetInfo
	(*PetTeam)(nil),                       // 2: Next.PetTeam
	(*PetSynchronInfo)(nil),               // 3: Next.PetSynchronInfo
	(*PetTeamInfo)(nil),                   // 4: Next.PetTeamInfo
	(*SharedPetTeamInfo)(nil),             // 5: Next.SharedPetTeamInfo
	(*SharedPetInfo)(nil),                 // 6: Next.SharedPetInfo
	(*AdjustedPetTeamInfo)(nil),           // 7: Next.AdjustedPetTeamInfo
	(*AdjustedPet)(nil),                   // 8: Next.AdjustedPet
	(*AdjustedPetSkill)(nil),              // 9: Next.AdjustedPetSkill
	(*RecommendPetTeamInfo)(nil),          // 10: Next.RecommendPetTeamInfo
	(*FriendPetTeamInfo)(nil),             // 11: Next.FriendPetTeamInfo
	(*FriendPetTeamIndex)(nil),            // 12: Next.FriendPetTeamIndex
	(*FriendPetTeamBufferFriendInfo)(nil), // 13: Next.FriendPetTeamBufferFriendInfo
	(*PetTypeInfo)(nil),                   // 14: Next.PetTypeInfo
	(*TrialPetBrief)(nil),                 // 15: Next.TrialPetBrief
	(*PetData)(nil),                       // 16: Next.PetData
}
var file_com_pet_team_proto_depIdxs = []int32{
	0,  // 0: Next.PetTeam_PetInfo.equip_infos:type_name -> Next.PetSkillEquipInfo
	14, // 1: Next.PetTeam_PetInfo.type:type_name -> Next.PetTypeInfo
	1,  // 2: Next.PetTeam.pet_infos:type_name -> Next.PetTeam_PetInfo
	15, // 3: Next.PetTeam.trial_pet:type_name -> Next.TrialPetBrief
	2,  // 4: Next.PetTeamInfo.teams:type_name -> Next.PetTeam
	3,  // 5: Next.PetTeamInfo.synchron:type_name -> Next.PetSynchronInfo
	6,  // 6: Next.SharedPetTeamInfo.pets:type_name -> Next.SharedPetInfo
	0,  // 7: Next.SharedPetInfo.skills:type_name -> Next.PetSkillEquipInfo
	14, // 8: Next.SharedPetInfo.type:type_name -> Next.PetTypeInfo
	8,  // 9: Next.AdjustedPetTeamInfo.pets:type_name -> Next.AdjustedPet
	9,  // 10: Next.AdjustedPet.skills:type_name -> Next.AdjustedPetSkill
	5,  // 11: Next.RecommendPetTeamInfo.pet_team_info:type_name -> Next.SharedPetTeamInfo
	16, // 12: Next.FriendPetTeamInfo.pets:type_name -> Next.PetData
	2,  // 13: Next.FriendPetTeamInfo.teams:type_name -> Next.PetTeam
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_com_pet_team_proto_init() }
func file_com_pet_team_proto_init() {
	if File_com_pet_team_proto != nil {
		return
	}
	file_com_pet_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_com_pet_team_proto_rawDesc), len(file_com_pet_team_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_com_pet_team_proto_goTypes,
		DependencyIndexes: file_com_pet_team_proto_depIdxs,
		MessageInfos:      file_com_pet_team_proto_msgTypes,
	}.Build()
	File_com_pet_team_proto = out.File
	file_com_pet_team_proto_goTypes = nil
	file_com_pet_team_proto_depIdxs = nil
}
