// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: com_base_types.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             *int32                 `protobuf:"varint,1,opt,name=x" json:"x,omitempty"`
	Y             *int32                 `protobuf:"varint,2,opt,name=y" json:"y,omitempty"`
	Z             *int32                 `protobuf:"varint,3,opt,name=z" json:"z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_com_base_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_com_base_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_com_base_types_proto_rawDescGZIP(), []int{0}
}

func (x *Position) GetX() int32 {
	if x != nil && x.X != nil {
		return *x.X
	}
	return 0
}

func (x *Position) GetY() int32 {
	if x != nil && x.Y != nil {
		return *x.Y
	}
	return 0
}

func (x *Position) GetZ() int32 {
	if x != nil && x.Z != nil {
		return *x.Z
	}
	return 0
}

type Position2D struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             *int32                 `protobuf:"varint,1,opt,name=x" json:"x,omitempty"`
	Y             *int32                 `protobuf:"varint,2,opt,name=y" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position2D) Reset() {
	*x = Position2D{}
	mi := &file_com_base_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position2D) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position2D) ProtoMessage() {}

func (x *Position2D) ProtoReflect() protoreflect.Message {
	mi := &file_com_base_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position2D.ProtoReflect.Descriptor instead.
func (*Position2D) Descriptor() ([]byte, []int) {
	return file_com_base_types_proto_rawDescGZIP(), []int{1}
}

func (x *Position2D) GetX() int32 {
	if x != nil && x.X != nil {
		return *x.X
	}
	return 0
}

func (x *Position2D) GetY() int32 {
	if x != nil && x.Y != nil {
		return *x.Y
	}
	return 0
}

type Point struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pos           *Position              `protobuf:"bytes,1,opt,name=pos" json:"pos,omitempty"`
	Dir           *Position              `protobuf:"bytes,2,opt,name=dir" json:"dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Point) Reset() {
	*x = Point{}
	mi := &file_com_base_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_com_base_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_com_base_types_proto_rawDescGZIP(), []int{2}
}

func (x *Point) GetPos() *Position {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *Point) GetDir() *Position {
	if x != nil {
		return x.Dir
	}
	return nil
}

type Rect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Beg           *Position              `protobuf:"bytes,1,opt,name=beg" json:"beg,omitempty"`
	Size          *Position              `protobuf:"bytes,2,opt,name=size" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rect) Reset() {
	*x = Rect{}
	mi := &file_com_base_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rect) ProtoMessage() {}

func (x *Rect) ProtoReflect() protoreflect.Message {
	mi := &file_com_base_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rect.ProtoReflect.Descriptor instead.
func (*Rect) Descriptor() ([]byte, []int) {
	return file_com_base_types_proto_rawDescGZIP(), []int{3}
}

func (x *Rect) GetBeg() *Position {
	if x != nil {
		return x.Beg
	}
	return nil
}

func (x *Rect) GetSize() *Position {
	if x != nil {
		return x.Size
	}
	return nil
}

type Rect2D struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Beg           *Position2D            `protobuf:"bytes,1,opt,name=beg" json:"beg,omitempty"`
	Size          *Position2D            `protobuf:"bytes,2,opt,name=size" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rect2D) Reset() {
	*x = Rect2D{}
	mi := &file_com_base_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rect2D) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rect2D) ProtoMessage() {}

func (x *Rect2D) ProtoReflect() protoreflect.Message {
	mi := &file_com_base_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rect2D.ProtoReflect.Descriptor instead.
func (*Rect2D) Descriptor() ([]byte, []int) {
	return file_com_base_types_proto_rawDescGZIP(), []int{4}
}

func (x *Rect2D) GetBeg() *Position2D {
	if x != nil {
		return x.Beg
	}
	return nil
}

func (x *Rect2D) GetSize() *Position2D {
	if x != nil {
		return x.Size
	}
	return nil
}

type GlassInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GlassType     *GlassType             `protobuf:"varint,1,opt,name=glass_type,json=glassType,enum=dataconfig.GlassType" json:"glass_type,omitempty"`
	GlassValue    *int32                 `protobuf:"varint,2,opt,name=glass_value,json=glassValue" json:"glass_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlassInfo) Reset() {
	*x = GlassInfo{}
	mi := &file_com_base_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlassInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlassInfo) ProtoMessage() {}

func (x *GlassInfo) ProtoReflect() protoreflect.Message {
	mi := &file_com_base_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlassInfo.ProtoReflect.Descriptor instead.
func (*GlassInfo) Descriptor() ([]byte, []int) {
	return file_com_base_types_proto_rawDescGZIP(), []int{5}
}

func (x *GlassInfo) GetGlassType() GlassType {
	if x != nil && x.GlassType != nil {
		return *x.GlassType
	}
	return GlassType_GT_NULL
}

func (x *GlassInfo) GetGlassValue() int32 {
	if x != nil && x.GlassValue != nil {
		return *x.GlassValue
	}
	return 0
}

type RecordItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cmd           *string                `protobuf:"bytes,1,opt,name=cmd" json:"cmd,omitempty"`
	CmdVal        *uint32                `protobuf:"varint,2,opt,name=cmd_val,json=cmdVal" json:"cmd_val,omitempty"`
	Content       []byte                 `protobuf:"bytes,3,opt,name=content" json:"content,omitempty"`
	WriteTime     []byte                 `protobuf:"bytes,4,opt,name=write_time,json=writeTime" json:"write_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordItem) Reset() {
	*x = RecordItem{}
	mi := &file_com_base_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordItem) ProtoMessage() {}

func (x *RecordItem) ProtoReflect() protoreflect.Message {
	mi := &file_com_base_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordItem.ProtoReflect.Descriptor instead.
func (*RecordItem) Descriptor() ([]byte, []int) {
	return file_com_base_types_proto_rawDescGZIP(), []int{6}
}

func (x *RecordItem) GetCmd() string {
	if x != nil && x.Cmd != nil {
		return *x.Cmd
	}
	return ""
}

func (x *RecordItem) GetCmdVal() uint32 {
	if x != nil && x.CmdVal != nil {
		return *x.CmdVal
	}
	return 0
}

func (x *RecordItem) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *RecordItem) GetWriteTime() []byte {
	if x != nil {
		return x.WriteTime
	}
	return nil
}

type RecordItemList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemList      []*RecordItem          `protobuf:"bytes,1,rep,name=item_list,json=itemList" json:"item_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordItemList) Reset() {
	*x = RecordItemList{}
	mi := &file_com_base_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordItemList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordItemList) ProtoMessage() {}

func (x *RecordItemList) ProtoReflect() protoreflect.Message {
	mi := &file_com_base_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordItemList.ProtoReflect.Descriptor instead.
func (*RecordItemList) Descriptor() ([]byte, []int) {
	return file_com_base_types_proto_rawDescGZIP(), []int{7}
}

func (x *RecordItemList) GetItemList() []*RecordItem {
	if x != nil {
		return x.ItemList
	}
	return nil
}

type RecordFileData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BattleId      *string                `protobuf:"bytes,1,opt,name=battle_id,json=battleId" json:"battle_id,omitempty"`
	Uin           *string                `protobuf:"bytes,2,opt,name=uin" json:"uin,omitempty"`
	BattleData    *RecordItemList        `protobuf:"bytes,5,opt,name=battle_data,json=battleData" json:"battle_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordFileData) Reset() {
	*x = RecordFileData{}
	mi := &file_com_base_types_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordFileData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordFileData) ProtoMessage() {}

func (x *RecordFileData) ProtoReflect() protoreflect.Message {
	mi := &file_com_base_types_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordFileData.ProtoReflect.Descriptor instead.
func (*RecordFileData) Descriptor() ([]byte, []int) {
	return file_com_base_types_proto_rawDescGZIP(), []int{8}
}

func (x *RecordFileData) GetBattleId() string {
	if x != nil && x.BattleId != nil {
		return *x.BattleId
	}
	return ""
}

func (x *RecordFileData) GetUin() string {
	if x != nil && x.Uin != nil {
		return *x.Uin
	}
	return ""
}

func (x *RecordFileData) GetBattleData() *RecordItemList {
	if x != nil {
		return x.BattleData
	}
	return nil
}

type PlayerSceneInfo struct {
	state                             protoimpl.MessageState `protogen:"open.v1"`
	CellId                            *uint64                `protobuf:"varint,1,opt,name=cell_id,json=cellId" json:"cell_id,omitempty"`
	Pt                                *Point                 `protobuf:"bytes,2,opt,name=pt" json:"pt,omitempty"`
	BelongCamp                        *uint32                `protobuf:"varint,3,opt,name=belong_camp,json=belongCamp" json:"belong_camp,omitempty"`
	EnteredCellInLastLoginProgress    *bool                  `protobuf:"varint,4,opt,name=entered_cell_in_last_login_progress,json=enteredCellInLastLoginProgress" json:"entered_cell_in_last_login_progress,omitempty"`
	KickoutTypeWhenScenesvrRecovering *int32                 `protobuf:"varint,5,opt,name=kickout_type_when_scenesvr_recovering,json=kickoutTypeWhenScenesvrRecovering" json:"kickout_type_when_scenesvr_recovering,omitempty"`
	DestroyFailedCellsvrBusppInstIds  []uint64               `protobuf:"varint,11,rep,name=destroy_failed_cellsvr_buspp_inst_ids,json=destroyFailedCellsvrBusppInstIds" json:"destroy_failed_cellsvr_buspp_inst_ids,omitempty"`
	TimeOfDay                         *int32                 `protobuf:"varint,12,opt,name=time_of_day,json=timeOfDay" json:"time_of_day,omitempty"`
	WeatherType                       *int32                 `protobuf:"varint,13,opt,name=weather_type,json=weatherType" json:"weather_type,omitempty"`
	CurrTime                          *int64                 `protobuf:"varint,14,opt,name=curr_time,json=currTime" json:"curr_time,omitempty"`
	unknownFields                     protoimpl.UnknownFields
	sizeCache                         protoimpl.SizeCache
}

func (x *PlayerSceneInfo) Reset() {
	*x = PlayerSceneInfo{}
	mi := &file_com_base_types_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerSceneInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerSceneInfo) ProtoMessage() {}

func (x *PlayerSceneInfo) ProtoReflect() protoreflect.Message {
	mi := &file_com_base_types_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerSceneInfo.ProtoReflect.Descriptor instead.
func (*PlayerSceneInfo) Descriptor() ([]byte, []int) {
	return file_com_base_types_proto_rawDescGZIP(), []int{9}
}

func (x *PlayerSceneInfo) GetCellId() uint64 {
	if x != nil && x.CellId != nil {
		return *x.CellId
	}
	return 0
}

func (x *PlayerSceneInfo) GetPt() *Point {
	if x != nil {
		return x.Pt
	}
	return nil
}

func (x *PlayerSceneInfo) GetBelongCamp() uint32 {
	if x != nil && x.BelongCamp != nil {
		return *x.BelongCamp
	}
	return 0
}

func (x *PlayerSceneInfo) GetEnteredCellInLastLoginProgress() bool {
	if x != nil && x.EnteredCellInLastLoginProgress != nil {
		return *x.EnteredCellInLastLoginProgress
	}
	return false
}

func (x *PlayerSceneInfo) GetKickoutTypeWhenScenesvrRecovering() int32 {
	if x != nil && x.KickoutTypeWhenScenesvrRecovering != nil {
		return *x.KickoutTypeWhenScenesvrRecovering
	}
	return 0
}

func (x *PlayerSceneInfo) GetDestroyFailedCellsvrBusppInstIds() []uint64 {
	if x != nil {
		return x.DestroyFailedCellsvrBusppInstIds
	}
	return nil
}

func (x *PlayerSceneInfo) GetTimeOfDay() int32 {
	if x != nil && x.TimeOfDay != nil {
		return *x.TimeOfDay
	}
	return 0
}

func (x *PlayerSceneInfo) GetWeatherType() int32 {
	if x != nil && x.WeatherType != nil {
		return *x.WeatherType
	}
	return 0
}

func (x *PlayerSceneInfo) GetCurrTime() int64 {
	if x != nil && x.CurrTime != nil {
		return *x.CurrTime
	}
	return 0
}

type OwlSanctuaryPetDiffInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ClosenessExp   *int32                 `protobuf:"varint,1,opt,name=closeness_exp,json=closenessExp" json:"closeness_exp,omitempty"`
	SpecialityData []int32                `protobuf:"varint,2,rep,name=speciality_data,json=specialityData" json:"speciality_data,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OwlSanctuaryPetDiffInfo) Reset() {
	*x = OwlSanctuaryPetDiffInfo{}
	mi := &file_com_base_types_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OwlSanctuaryPetDiffInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OwlSanctuaryPetDiffInfo) ProtoMessage() {}

func (x *OwlSanctuaryPetDiffInfo) ProtoReflect() protoreflect.Message {
	mi := &file_com_base_types_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OwlSanctuaryPetDiffInfo.ProtoReflect.Descriptor instead.
func (*OwlSanctuaryPetDiffInfo) Descriptor() ([]byte, []int) {
	return file_com_base_types_proto_rawDescGZIP(), []int{10}
}

func (x *OwlSanctuaryPetDiffInfo) GetClosenessExp() int32 {
	if x != nil && x.ClosenessExp != nil {
		return *x.ClosenessExp
	}
	return 0
}

func (x *OwlSanctuaryPetDiffInfo) GetSpecialityData() []int32 {
	if x != nil {
		return x.SpecialityData
	}
	return nil
}

var File_com_base_types_proto protoreflect.FileDescriptor

const file_com_base_types_proto_rawDesc = "" +
	"\n" +
	"\x14com_base_types.proto\x12\x04Next\x1a\x0exls_enum.proto\"4\n" +
	"\bPosition\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x05R\x01z\"(\n" +
	"\n" +
	"Position2D\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\"K\n" +
	"\x05Point\x12 \n" +
	"\x03pos\x18\x01 \x01(\v2\x0e.Next.PositionR\x03pos\x12 \n" +
	"\x03dir\x18\x02 \x01(\v2\x0e.Next.PositionR\x03dir\"L\n" +
	"\x04Rect\x12 \n" +
	"\x03beg\x18\x01 \x01(\v2\x0e.Next.PositionR\x03beg\x12\"\n" +
	"\x04size\x18\x02 \x01(\v2\x0e.Next.PositionR\x04size\"R\n" +
	"\x06Rect2D\x12\"\n" +
	"\x03beg\x18\x01 \x01(\v2\x10.Next.Position2DR\x03beg\x12$\n" +
	"\x04size\x18\x02 \x01(\v2\x10.Next.Position2DR\x04size\"b\n" +
	"\tGlassInfo\x124\n" +
	"\n" +
	"glass_type\x18\x01 \x01(\x0e2\x15.dataconfig.GlassTypeR\tglassType\x12\x1f\n" +
	"\vglass_value\x18\x02 \x01(\x05R\n" +
	"glassValue\"p\n" +
	"\n" +
	"RecordItem\x12\x10\n" +
	"\x03cmd\x18\x01 \x01(\tR\x03cmd\x12\x17\n" +
	"\acmd_val\x18\x02 \x01(\rR\x06cmdVal\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\x12\x1d\n" +
	"\n" +
	"write_time\x18\x04 \x01(\fR\twriteTime\"?\n" +
	"\x0eRecordItemList\x12-\n" +
	"\titem_list\x18\x01 \x03(\v2\x10.Next.RecordItemR\bitemList\"v\n" +
	"\x0eRecordFileData\x12\x1b\n" +
	"\tbattle_id\x18\x01 \x01(\tR\bbattleId\x12\x10\n" +
	"\x03uin\x18\x02 \x01(\tR\x03uin\x125\n" +
	"\vbattle_data\x18\x05 \x01(\v2\x14.Next.RecordItemListR\n" +
	"battleData\"\xb8\x03\n" +
	"\x0fPlayerSceneInfo\x12\x17\n" +
	"\acell_id\x18\x01 \x01(\x04R\x06cellId\x12\x1b\n" +
	"\x02pt\x18\x02 \x01(\v2\v.Next.PointR\x02pt\x12\x1f\n" +
	"\vbelong_camp\x18\x03 \x01(\rR\n" +
	"belongCamp\x12K\n" +
	"#entered_cell_in_last_login_progress\x18\x04 \x01(\bR\x1eenteredCellInLastLoginProgress\x12P\n" +
	"%kickout_type_when_scenesvr_recovering\x18\x05 \x01(\x05R!kickoutTypeWhenScenesvrRecovering\x12O\n" +
	"%destroy_failed_cellsvr_buspp_inst_ids\x18\v \x03(\x04R destroyFailedCellsvrBusppInstIds\x12\x1e\n" +
	"\vtime_of_day\x18\f \x01(\x05R\ttimeOfDay\x12!\n" +
	"\fweather_type\x18\r \x01(\x05R\vweatherType\x12\x1b\n" +
	"\tcurr_time\x18\x0e \x01(\x03R\bcurrTime\"g\n" +
	"\x17OwlSanctuaryPetDiffInfo\x12#\n" +
	"\rcloseness_exp\x18\x01 \x01(\x05R\fclosenessExp\x12'\n" +
	"\x0fspeciality_data\x18\x02 \x03(\x05R\x0especialityData"

var (
	file_com_base_types_proto_rawDescOnce sync.Once
	file_com_base_types_proto_rawDescData []byte
)

func file_com_base_types_proto_rawDescGZIP() []byte {
	file_com_base_types_proto_rawDescOnce.Do(func() {
		file_com_base_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_com_base_types_proto_rawDesc), len(file_com_base_types_proto_rawDesc)))
	})
	return file_com_base_types_proto_rawDescData
}

var file_com_base_types_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_com_base_types_proto_goTypes = []any{
	(*Position)(nil),                // 0: Next.Position
	(*Position2D)(nil),              // 1: Next.Position2D
	(*Point)(nil),                   // 2: Next.Point
	(*Rect)(nil),                    // 3: Next.Rect
	(*Rect2D)(nil),                  // 4: Next.Rect2D
	(*GlassInfo)(nil),               // 5: Next.GlassInfo
	(*RecordItem)(nil),              // 6: Next.RecordItem
	(*RecordItemList)(nil),          // 7: Next.RecordItemList
	(*RecordFileData)(nil),          // 8: Next.RecordFileData
	(*PlayerSceneInfo)(nil),         // 9: Next.PlayerSceneInfo
	(*OwlSanctuaryPetDiffInfo)(nil), // 10: Next.OwlSanctuaryPetDiffInfo
	(GlassType)(0),                  // 11: dataconfig.GlassType
}
var file_com_base_types_proto_depIdxs = []int32{
	0,  // 0: Next.Point.pos:type_name -> Next.Position
	0,  // 1: Next.Point.dir:type_name -> Next.Position
	0,  // 2: Next.Rect.beg:type_name -> Next.Position
	0,  // 3: Next.Rect.size:type_name -> Next.Position
	1,  // 4: Next.Rect2D.beg:type_name -> Next.Position2D
	1,  // 5: Next.Rect2D.size:type_name -> Next.Position2D
	11, // 6: Next.GlassInfo.glass_type:type_name -> dataconfig.GlassType
	6,  // 7: Next.RecordItemList.item_list:type_name -> Next.RecordItem
	7,  // 8: Next.RecordFileData.battle_data:type_name -> Next.RecordItemList
	2,  // 9: Next.PlayerSceneInfo.pt:type_name -> Next.Point
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_com_base_types_proto_init() }
func file_com_base_types_proto_init() {
	if File_com_base_types_proto != nil {
		return
	}
	file_xls_enum_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_com_base_types_proto_rawDesc), len(file_com_base_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_com_base_types_proto_goTypes,
		DependencyIndexes: file_com_base_types_proto_depIdxs,
		MessageInfos:      file_com_base_types_proto_msgTypes,
	}.Build()
	File_com_base_types_proto = out.File
	file_com_base_types_proto_goTypes = nil
	file_com_base_types_proto_depIdxs = nil
}
