// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: com_pet_skill.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PetSkillInfo_COUNT_LIMIT int32

const (
	PetSkillInfo_SKILL_DATA_COUNT PetSkillInfo_COUNT_LIMIT = 200
)

// Enum value maps for PetSkillInfo_COUNT_LIMIT.
var (
	PetSkillInfo_COUNT_LIMIT_name = map[int32]string{
		200: "SKILL_DATA_COUNT",
	}
	PetSkillInfo_COUNT_LIMIT_value = map[string]int32{
		"SKILL_DATA_COUNT": 200,
	}
)

func (x PetSkillInfo_COUNT_LIMIT) Enum() *PetSkillInfo_COUNT_LIMIT {
	p := new(PetSkillInfo_COUNT_LIMIT)
	*p = x
	return p
}

func (x PetSkillInfo_COUNT_LIMIT) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PetSkillInfo_COUNT_LIMIT) Descriptor() protoreflect.EnumDescriptor {
	return file_com_pet_skill_proto_enumTypes[0].Descriptor()
}

func (PetSkillInfo_COUNT_LIMIT) Type() protoreflect.EnumType {
	return &file_com_pet_skill_proto_enumTypes[0]
}

func (x PetSkillInfo_COUNT_LIMIT) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *PetSkillInfo_COUNT_LIMIT) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = PetSkillInfo_COUNT_LIMIT(num)
	return nil
}

// Deprecated: Use PetSkillInfo_COUNT_LIMIT.Descriptor instead.
func (PetSkillInfo_COUNT_LIMIT) EnumDescriptor() ([]byte, []int) {
	return file_com_pet_skill_proto_rawDescGZIP(), []int{4, 0}
}

type PetCarryonInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CarryonId     *uint32                `protobuf:"varint,1,opt,name=carryon_id,json=carryonId" json:"carryon_id,omitempty"`
	CarryonIdx    *uint32                `protobuf:"varint,2,opt,name=carryon_idx,json=carryonIdx" json:"carryon_idx,omitempty"`
	PetGid        *uint32                `protobuf:"varint,3,opt,name=pet_gid,json=petGid" json:"pet_gid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetCarryonInfo) Reset() {
	*x = PetCarryonInfo{}
	mi := &file_com_pet_skill_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetCarryonInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetCarryonInfo) ProtoMessage() {}

func (x *PetCarryonInfo) ProtoReflect() protoreflect.Message {
	mi := &file_com_pet_skill_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetCarryonInfo.ProtoReflect.Descriptor instead.
func (*PetCarryonInfo) Descriptor() ([]byte, []int) {
	return file_com_pet_skill_proto_rawDescGZIP(), []int{0}
}

func (x *PetCarryonInfo) GetCarryonId() uint32 {
	if x != nil && x.CarryonId != nil {
		return *x.CarryonId
	}
	return 0
}

func (x *PetCarryonInfo) GetCarryonIdx() uint32 {
	if x != nil && x.CarryonIdx != nil {
		return *x.CarryonIdx
	}
	return 0
}

func (x *PetCarryonInfo) GetPetGid() uint32 {
	if x != nil && x.PetGid != nil {
		return *x.PetGid
	}
	return 0
}

type PetSkillData struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               *uint32                `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Type             *uint32                `protobuf:"varint,2,opt,name=type" json:"type,omitempty"`
	IsLearned        *bool                  `protobuf:"varint,3,opt,name=is_learned,json=isLearned" json:"is_learned,omitempty"`
	IsEquipped       *bool                  `protobuf:"varint,4,opt,name=is_equipped,json=isEquipped" json:"is_equipped,omitempty"`
	Pos              *uint32                `protobuf:"varint,5,opt,name=pos" json:"pos,omitempty"`
	SeasonId         *int32                 `protobuf:"varint,6,opt,name=season_id,json=seasonId" json:"season_id,omitempty"`
	UnlockNeedLv     *uint32                `protobuf:"varint,8,opt,name=unlock_need_lv,json=unlockNeedLv" json:"unlock_need_lv,omitempty"`
	RawId            *uint32                `protobuf:"varint,11,opt,name=raw_id,json=rawId" json:"raw_id,omitempty"`
	CarryonInfo      *PetCarryonInfo        `protobuf:"bytes,12,opt,name=carryon_info,json=carryonInfo" json:"carryon_info,omitempty"`
	ConfIdx          *uint32                `protobuf:"varint,13,opt,name=conf_idx,json=confIdx" json:"conf_idx,omitempty"`
	SkillSrc         *uint32                `protobuf:"varint,14,opt,name=skill_src,json=skillSrc" json:"skill_src,omitempty"`
	UnlockNeedBaseId *uint32                `protobuf:"varint,15,opt,name=unlock_need_base_id,json=unlockNeedBaseId" json:"unlock_need_base_id,omitempty"`
	UseTimes         *int32                 `protobuf:"varint,16,opt,name=use_times,json=useTimes" json:"use_times,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PetSkillData) Reset() {
	*x = PetSkillData{}
	mi := &file_com_pet_skill_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetSkillData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetSkillData) ProtoMessage() {}

func (x *PetSkillData) ProtoReflect() protoreflect.Message {
	mi := &file_com_pet_skill_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetSkillData.ProtoReflect.Descriptor instead.
func (*PetSkillData) Descriptor() ([]byte, []int) {
	return file_com_pet_skill_proto_rawDescGZIP(), []int{1}
}

func (x *PetSkillData) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *PetSkillData) GetType() uint32 {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return 0
}

func (x *PetSkillData) GetIsLearned() bool {
	if x != nil && x.IsLearned != nil {
		return *x.IsLearned
	}
	return false
}

func (x *PetSkillData) GetIsEquipped() bool {
	if x != nil && x.IsEquipped != nil {
		return *x.IsEquipped
	}
	return false
}

func (x *PetSkillData) GetPos() uint32 {
	if x != nil && x.Pos != nil {
		return *x.Pos
	}
	return 0
}

func (x *PetSkillData) GetSeasonId() int32 {
	if x != nil && x.SeasonId != nil {
		return *x.SeasonId
	}
	return 0
}

func (x *PetSkillData) GetUnlockNeedLv() uint32 {
	if x != nil && x.UnlockNeedLv != nil {
		return *x.UnlockNeedLv
	}
	return 0
}

func (x *PetSkillData) GetRawId() uint32 {
	if x != nil && x.RawId != nil {
		return *x.RawId
	}
	return 0
}

func (x *PetSkillData) GetCarryonInfo() *PetCarryonInfo {
	if x != nil {
		return x.CarryonInfo
	}
	return nil
}

func (x *PetSkillData) GetConfIdx() uint32 {
	if x != nil && x.ConfIdx != nil {
		return *x.ConfIdx
	}
	return 0
}

func (x *PetSkillData) GetSkillSrc() uint32 {
	if x != nil && x.SkillSrc != nil {
		return *x.SkillSrc
	}
	return 0
}

func (x *PetSkillData) GetUnlockNeedBaseId() uint32 {
	if x != nil && x.UnlockNeedBaseId != nil {
		return *x.UnlockNeedBaseId
	}
	return 0
}

func (x *PetSkillData) GetUseTimes() int32 {
	if x != nil && x.UseTimes != nil {
		return *x.UseTimes
	}
	return 0
}

type PetSkillRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkillId       *uint32                `protobuf:"varint,1,opt,name=skill_id,json=skillId" json:"skill_id,omitempty"`
	UseTimes      *int32                 `protobuf:"varint,2,opt,name=use_times,json=useTimes" json:"use_times,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetSkillRecord) Reset() {
	*x = PetSkillRecord{}
	mi := &file_com_pet_skill_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetSkillRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetSkillRecord) ProtoMessage() {}

func (x *PetSkillRecord) ProtoReflect() protoreflect.Message {
	mi := &file_com_pet_skill_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetSkillRecord.ProtoReflect.Descriptor instead.
func (*PetSkillRecord) Descriptor() ([]byte, []int) {
	return file_com_pet_skill_proto_rawDescGZIP(), []int{2}
}

func (x *PetSkillRecord) GetSkillId() uint32 {
	if x != nil && x.SkillId != nil {
		return *x.SkillId
	}
	return 0
}

func (x *PetSkillRecord) GetUseTimes() int32 {
	if x != nil && x.UseTimes != nil {
		return *x.UseTimes
	}
	return 0
}

type SkillRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uin           *uint32                `protobuf:"varint,1,opt,name=uin" json:"uin,omitempty"`
	SkillId       *uint32                `protobuf:"varint,2,opt,name=skill_id,json=skillId" json:"skill_id,omitempty"`
	Result0       *uint32                `protobuf:"varint,3,opt,name=result0" json:"result0,omitempty"`
	Result1       *uint32                `protobuf:"varint,4,opt,name=result1" json:"result1,omitempty"`
	Result2       *uint32                `protobuf:"varint,5,opt,name=result2" json:"result2,omitempty"`
	RestraintCnt1 *int32                 `protobuf:"varint,6,opt,name=restraint_cnt1,json=restraintCnt1" json:"restraint_cnt1,omitempty"`
	RestraintCnt2 *int32                 `protobuf:"varint,7,opt,name=restraint_cnt2,json=restraintCnt2" json:"restraint_cnt2,omitempty"`
	RestraintCnt3 *int32                 `protobuf:"varint,8,opt,name=restraint_cnt3,json=restraintCnt3" json:"restraint_cnt3,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillRecord) Reset() {
	*x = SkillRecord{}
	mi := &file_com_pet_skill_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillRecord) ProtoMessage() {}

func (x *SkillRecord) ProtoReflect() protoreflect.Message {
	mi := &file_com_pet_skill_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillRecord.ProtoReflect.Descriptor instead.
func (*SkillRecord) Descriptor() ([]byte, []int) {
	return file_com_pet_skill_proto_rawDescGZIP(), []int{3}
}

func (x *SkillRecord) GetUin() uint32 {
	if x != nil && x.Uin != nil {
		return *x.Uin
	}
	return 0
}

func (x *SkillRecord) GetSkillId() uint32 {
	if x != nil && x.SkillId != nil {
		return *x.SkillId
	}
	return 0
}

func (x *SkillRecord) GetResult0() uint32 {
	if x != nil && x.Result0 != nil {
		return *x.Result0
	}
	return 0
}

func (x *SkillRecord) GetResult1() uint32 {
	if x != nil && x.Result1 != nil {
		return *x.Result1
	}
	return 0
}

func (x *SkillRecord) GetResult2() uint32 {
	if x != nil && x.Result2 != nil {
		return *x.Result2
	}
	return 0
}

func (x *SkillRecord) GetRestraintCnt1() int32 {
	if x != nil && x.RestraintCnt1 != nil {
		return *x.RestraintCnt1
	}
	return 0
}

func (x *SkillRecord) GetRestraintCnt2() int32 {
	if x != nil && x.RestraintCnt2 != nil {
		return *x.RestraintCnt2
	}
	return 0
}

func (x *SkillRecord) GetRestraintCnt3() int32 {
	if x != nil && x.RestraintCnt3 != nil {
		return *x.RestraintCnt3
	}
	return 0
}

type PetSkillInfo struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	SkillData                []*PetSkillData        `protobuf:"bytes,1,rep,name=skill_data,json=skillData" json:"skill_data,omitempty"`
	HappySkillIds            []uint32               `protobuf:"varint,2,rep,name=happy_skill_ids,json=happySkillIds" json:"happy_skill_ids,omitempty"`
	AngrySkillIds            []uint32               `protobuf:"varint,3,rep,name=angry_skill_ids,json=angrySkillIds" json:"angry_skill_ids,omitempty"`
	UnlearnedSkillUseRecords []*PetSkillRecord      `protobuf:"bytes,4,rep,name=unlearned_skill_use_records,json=unlearnedSkillUseRecords" json:"unlearned_skill_use_records,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *PetSkillInfo) Reset() {
	*x = PetSkillInfo{}
	mi := &file_com_pet_skill_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetSkillInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetSkillInfo) ProtoMessage() {}

func (x *PetSkillInfo) ProtoReflect() protoreflect.Message {
	mi := &file_com_pet_skill_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetSkillInfo.ProtoReflect.Descriptor instead.
func (*PetSkillInfo) Descriptor() ([]byte, []int) {
	return file_com_pet_skill_proto_rawDescGZIP(), []int{4}
}

func (x *PetSkillInfo) GetSkillData() []*PetSkillData {
	if x != nil {
		return x.SkillData
	}
	return nil
}

func (x *PetSkillInfo) GetHappySkillIds() []uint32 {
	if x != nil {
		return x.HappySkillIds
	}
	return nil
}

func (x *PetSkillInfo) GetAngrySkillIds() []uint32 {
	if x != nil {
		return x.AngrySkillIds
	}
	return nil
}

func (x *PetSkillInfo) GetUnlearnedSkillUseRecords() []*PetSkillRecord {
	if x != nil {
		return x.UnlearnedSkillUseRecords
	}
	return nil
}

type PetPosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PetId         *uint32                `protobuf:"varint,1,opt,name=pet_id,json=petId" json:"pet_id,omitempty"`
	Pos           *Position              `protobuf:"bytes,2,opt,name=pos" json:"pos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetPosition) Reset() {
	*x = PetPosition{}
	mi := &file_com_pet_skill_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetPosition) ProtoMessage() {}

func (x *PetPosition) ProtoReflect() protoreflect.Message {
	mi := &file_com_pet_skill_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetPosition.ProtoReflect.Descriptor instead.
func (*PetPosition) Descriptor() ([]byte, []int) {
	return file_com_pet_skill_proto_rawDescGZIP(), []int{5}
}

func (x *PetPosition) GetPetId() uint32 {
	if x != nil && x.PetId != nil {
		return *x.PetId
	}
	return 0
}

func (x *PetPosition) GetPos() *Position {
	if x != nil {
		return x.Pos
	}
	return nil
}

type CastInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkillId       *uint32                `protobuf:"varint,1,opt,name=skill_id,json=skillId" json:"skill_id,omitempty"`
	AuraConfId    *uint32                `protobuf:"varint,2,opt,name=aura_conf_id,json=auraConfId" json:"aura_conf_id,omitempty"`
	GroupId       *uint32                `protobuf:"varint,3,opt,name=group_id,json=groupId" json:"group_id,omitempty"`
	CastMoment    *uint32                `protobuf:"varint,4,opt,name=cast_moment,json=castMoment" json:"cast_moment,omitempty"`
	PetBaseId     *uint32                `protobuf:"varint,5,opt,name=pet_base_id,json=petBaseId" json:"pet_base_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CastInfo) Reset() {
	*x = CastInfo{}
	mi := &file_com_pet_skill_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CastInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CastInfo) ProtoMessage() {}

func (x *CastInfo) ProtoReflect() protoreflect.Message {
	mi := &file_com_pet_skill_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CastInfo.ProtoReflect.Descriptor instead.
func (*CastInfo) Descriptor() ([]byte, []int) {
	return file_com_pet_skill_proto_rawDescGZIP(), []int{6}
}

func (x *CastInfo) GetSkillId() uint32 {
	if x != nil && x.SkillId != nil {
		return *x.SkillId
	}
	return 0
}

func (x *CastInfo) GetAuraConfId() uint32 {
	if x != nil && x.AuraConfId != nil {
		return *x.AuraConfId
	}
	return 0
}

func (x *CastInfo) GetGroupId() uint32 {
	if x != nil && x.GroupId != nil {
		return *x.GroupId
	}
	return 0
}

func (x *CastInfo) GetCastMoment() uint32 {
	if x != nil && x.CastMoment != nil {
		return *x.CastMoment
	}
	return 0
}

func (x *CastInfo) GetPetBaseId() uint32 {
	if x != nil && x.PetBaseId != nil {
		return *x.PetBaseId
	}
	return 0
}

type PetCastAura struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PetPosInfo    *PetPosition           `protobuf:"bytes,1,opt,name=pet_pos_info,json=petPosInfo" json:"pet_pos_info,omitempty"`
	CastInfo      []*CastInfo            `protobuf:"bytes,2,rep,name=cast_info,json=castInfo" json:"cast_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetCastAura) Reset() {
	*x = PetCastAura{}
	mi := &file_com_pet_skill_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetCastAura) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetCastAura) ProtoMessage() {}

func (x *PetCastAura) ProtoReflect() protoreflect.Message {
	mi := &file_com_pet_skill_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetCastAura.ProtoReflect.Descriptor instead.
func (*PetCastAura) Descriptor() ([]byte, []int) {
	return file_com_pet_skill_proto_rawDescGZIP(), []int{7}
}

func (x *PetCastAura) GetPetPosInfo() *PetPosition {
	if x != nil {
		return x.PetPosInfo
	}
	return nil
}

func (x *PetCastAura) GetCastInfo() []*CastInfo {
	if x != nil {
		return x.CastInfo
	}
	return nil
}

type BattleRemoveAuraInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RemoveAuraEffect []uint32               `protobuf:"varint,1,rep,name=remove_aura_effect,json=removeAuraEffect" json:"remove_aura_effect,omitempty"`
	PetBaseId        *uint32                `protobuf:"varint,2,opt,name=pet_base_id,json=petBaseId" json:"pet_base_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BattleRemoveAuraInfo) Reset() {
	*x = BattleRemoveAuraInfo{}
	mi := &file_com_pet_skill_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleRemoveAuraInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleRemoveAuraInfo) ProtoMessage() {}

func (x *BattleRemoveAuraInfo) ProtoReflect() protoreflect.Message {
	mi := &file_com_pet_skill_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleRemoveAuraInfo.ProtoReflect.Descriptor instead.
func (*BattleRemoveAuraInfo) Descriptor() ([]byte, []int) {
	return file_com_pet_skill_proto_rawDescGZIP(), []int{8}
}

func (x *BattleRemoveAuraInfo) GetRemoveAuraEffect() []uint32 {
	if x != nil {
		return x.RemoveAuraEffect
	}
	return nil
}

func (x *BattleRemoveAuraInfo) GetPetBaseId() uint32 {
	if x != nil && x.PetBaseId != nil {
		return *x.PetBaseId
	}
	return 0
}

type PetRemoveAura struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	PetPosInfo    *PetPosition            `protobuf:"bytes,1,opt,name=pet_pos_info,json=petPosInfo" json:"pet_pos_info,omitempty"`
	RemoveInfo    []*BattleRemoveAuraInfo `protobuf:"bytes,2,rep,name=remove_info,json=removeInfo" json:"remove_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetRemoveAura) Reset() {
	*x = PetRemoveAura{}
	mi := &file_com_pet_skill_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetRemoveAura) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetRemoveAura) ProtoMessage() {}

func (x *PetRemoveAura) ProtoReflect() protoreflect.Message {
	mi := &file_com_pet_skill_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetRemoveAura.ProtoReflect.Descriptor instead.
func (*PetRemoveAura) Descriptor() ([]byte, []int) {
	return file_com_pet_skill_proto_rawDescGZIP(), []int{9}
}

func (x *PetRemoveAura) GetPetPosInfo() *PetPosition {
	if x != nil {
		return x.PetPosInfo
	}
	return nil
}

func (x *PetRemoveAura) GetRemoveInfo() []*BattleRemoveAuraInfo {
	if x != nil {
		return x.RemoveInfo
	}
	return nil
}

var File_com_pet_skill_proto protoreflect.FileDescriptor

const file_com_pet_skill_proto_rawDesc = "" +
	"\n" +
	"\x13com_pet_skill.proto\x12\x04Next\x1a\x14com_base_types.proto\x1a\x0exls_enum.proto\"i\n" +
	"\x0ePetCarryonInfo\x12\x1d\n" +
	"\n" +
	"carryon_id\x18\x01 \x01(\rR\tcarryonId\x12\x1f\n" +
	"\vcarryon_idx\x18\x02 \x01(\rR\n" +
	"carryonIdx\x12\x17\n" +
	"\apet_gid\x18\x03 \x01(\rR\x06petGid\"\x9b\x03\n" +
	"\fPetSkillData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\rR\x04type\x12\x1d\n" +
	"\n" +
	"is_learned\x18\x03 \x01(\bR\tisLearned\x12\x1f\n" +
	"\vis_equipped\x18\x04 \x01(\bR\n" +
	"isEquipped\x12\x10\n" +
	"\x03pos\x18\x05 \x01(\rR\x03pos\x12\x1b\n" +
	"\tseason_id\x18\x06 \x01(\x05R\bseasonId\x12$\n" +
	"\x0eunlock_need_lv\x18\b \x01(\rR\funlockNeedLv\x12\x15\n" +
	"\x06raw_id\x18\v \x01(\rR\x05rawId\x127\n" +
	"\fcarryon_info\x18\f \x01(\v2\x14.Next.PetCarryonInfoR\vcarryonInfo\x12\x19\n" +
	"\bconf_idx\x18\r \x01(\rR\aconfIdx\x12\x1b\n" +
	"\tskill_src\x18\x0e \x01(\rR\bskillSrc\x12-\n" +
	"\x13unlock_need_base_id\x18\x0f \x01(\rR\x10unlockNeedBaseId\x12\x1b\n" +
	"\tuse_times\x18\x10 \x01(\x05R\buseTimes\"H\n" +
	"\x0ePetSkillRecord\x12\x19\n" +
	"\bskill_id\x18\x01 \x01(\rR\askillId\x12\x1b\n" +
	"\tuse_times\x18\x02 \x01(\x05R\buseTimes\"\xfd\x01\n" +
	"\vSkillRecord\x12\x10\n" +
	"\x03uin\x18\x01 \x01(\rR\x03uin\x12\x19\n" +
	"\bskill_id\x18\x02 \x01(\rR\askillId\x12\x18\n" +
	"\aresult0\x18\x03 \x01(\rR\aresult0\x12\x18\n" +
	"\aresult1\x18\x04 \x01(\rR\aresult1\x12\x18\n" +
	"\aresult2\x18\x05 \x01(\rR\aresult2\x12%\n" +
	"\x0erestraint_cnt1\x18\x06 \x01(\x05R\rrestraintCnt1\x12%\n" +
	"\x0erestraint_cnt2\x18\a \x01(\x05R\rrestraintCnt2\x12%\n" +
	"\x0erestraint_cnt3\x18\b \x01(\x05R\rrestraintCnt3\"\x8c\x02\n" +
	"\fPetSkillInfo\x121\n" +
	"\n" +
	"skill_data\x18\x01 \x03(\v2\x12.Next.PetSkillDataR\tskillData\x12&\n" +
	"\x0fhappy_skill_ids\x18\x02 \x03(\rR\rhappySkillIds\x12&\n" +
	"\x0fangry_skill_ids\x18\x03 \x03(\rR\rangrySkillIds\x12S\n" +
	"\x1bunlearned_skill_use_records\x18\x04 \x03(\v2\x14.Next.PetSkillRecordR\x18unlearnedSkillUseRecords\"$\n" +
	"\vCOUNT_LIMIT\x12\x15\n" +
	"\x10SKILL_DATA_COUNT\x10\xc8\x01\"F\n" +
	"\vPetPosition\x12\x15\n" +
	"\x06pet_id\x18\x01 \x01(\rR\x05petId\x12 \n" +
	"\x03pos\x18\x02 \x01(\v2\x0e.Next.PositionR\x03pos\"\xa3\x01\n" +
	"\bCastInfo\x12\x19\n" +
	"\bskill_id\x18\x01 \x01(\rR\askillId\x12 \n" +
	"\faura_conf_id\x18\x02 \x01(\rR\n" +
	"auraConfId\x12\x19\n" +
	"\bgroup_id\x18\x03 \x01(\rR\agroupId\x12\x1f\n" +
	"\vcast_moment\x18\x04 \x01(\rR\n" +
	"castMoment\x12\x1e\n" +
	"\vpet_base_id\x18\x05 \x01(\rR\tpetBaseId\"o\n" +
	"\vPetCastAura\x123\n" +
	"\fpet_pos_info\x18\x01 \x01(\v2\x11.Next.PetPositionR\n" +
	"petPosInfo\x12+\n" +
	"\tcast_info\x18\x02 \x03(\v2\x0e.Next.CastInfoR\bcastInfo\"d\n" +
	"\x14BattleRemoveAuraInfo\x12,\n" +
	"\x12remove_aura_effect\x18\x01 \x03(\rR\x10removeAuraEffect\x12\x1e\n" +
	"\vpet_base_id\x18\x02 \x01(\rR\tpetBaseId\"\x81\x01\n" +
	"\rPetRemoveAura\x123\n" +
	"\fpet_pos_info\x18\x01 \x01(\v2\x11.Next.PetPositionR\n" +
	"petPosInfo\x12;\n" +
	"\vremove_info\x18\x02 \x03(\v2\x1a.Next.BattleRemoveAuraInfoR\n" +
	"removeInfo"

var (
	file_com_pet_skill_proto_rawDescOnce sync.Once
	file_com_pet_skill_proto_rawDescData []byte
)

func file_com_pet_skill_proto_rawDescGZIP() []byte {
	file_com_pet_skill_proto_rawDescOnce.Do(func() {
		file_com_pet_skill_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_com_pet_skill_proto_rawDesc), len(file_com_pet_skill_proto_rawDesc)))
	})
	return file_com_pet_skill_proto_rawDescData
}

var file_com_pet_skill_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_com_pet_skill_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_com_pet_skill_proto_goTypes = []any{
	(PetSkillInfo_COUNT_LIMIT)(0), // 0: Next.PetSkillInfo.COUNT_LIMIT
	(*PetCarryonInfo)(nil),        // 1: Next.PetCarryonInfo
	(*PetSkillData)(nil),          // 2: Next.PetSkillData
	(*PetSkillRecord)(nil),        // 3: Next.PetSkillRecord
	(*SkillRecord)(nil),           // 4: Next.SkillRecord
	(*PetSkillInfo)(nil),          // 5: Next.PetSkillInfo
	(*PetPosition)(nil),           // 6: Next.PetPosition
	(*CastInfo)(nil),              // 7: Next.CastInfo
	(*PetCastAura)(nil),           // 8: Next.PetCastAura
	(*BattleRemoveAuraInfo)(nil),  // 9: Next.BattleRemoveAuraInfo
	(*PetRemoveAura)(nil),         // 10: Next.PetRemoveAura
	(*Position)(nil),              // 11: Next.Position
}
var file_com_pet_skill_proto_depIdxs = []int32{
	1,  // 0: Next.PetSkillData.carryon_info:type_name -> Next.PetCarryonInfo
	2,  // 1: Next.PetSkillInfo.skill_data:type_name -> Next.PetSkillData
	3,  // 2: Next.PetSkillInfo.unlearned_skill_use_records:type_name -> Next.PetSkillRecord
	11, // 3: Next.PetPosition.pos:type_name -> Next.Position
	6,  // 4: Next.PetCastAura.pet_pos_info:type_name -> Next.PetPosition
	7,  // 5: Next.PetCastAura.cast_info:type_name -> Next.CastInfo
	6,  // 6: Next.PetRemoveAura.pet_pos_info:type_name -> Next.PetPosition
	9,  // 7: Next.PetRemoveAura.remove_info:type_name -> Next.BattleRemoveAuraInfo
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_com_pet_skill_proto_init() }
func file_com_pet_skill_proto_init() {
	if File_com_pet_skill_proto != nil {
		return
	}
	file_com_base_types_proto_init()
	file_xls_enum_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_com_pet_skill_proto_rawDesc), len(file_com_pet_skill_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_com_pet_skill_proto_goTypes,
		DependencyIndexes: file_com_pet_skill_proto_depIdxs,
		EnumInfos:         file_com_pet_skill_proto_enumTypes,
		MessageInfos:      file_com_pet_skill_proto_msgTypes,
	}.Build()
	File_com_pet_skill_proto = out.File
	file_com_pet_skill_proto_goTypes = nil
	file_com_pet_skill_proto_depIdxs = nil
}
