// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: com_battle_enum.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BattleTaskState int32

const (
	BattleTaskState_BTS_UNKNOW  BattleTaskState = 0
	BattleTaskState_BTS_SUCCESS BattleTaskState = 1
	BattleTaskState_BTS_FAIL    BattleTaskState = 2
)

// Enum value maps for BattleTaskState.
var (
	BattleTaskState_name = map[int32]string{
		0: "BTS_UNKNOW",
		1: "BTS_SUCCESS",
		2: "BTS_FAIL",
	}
	BattleTaskState_value = map[string]int32{
		"BTS_UNKNOW":  0,
		"BTS_SUCCESS": 1,
		"BTS_FAIL":    2,
	}
)

func (x BattleTaskState) Enum() *BattleTaskState {
	p := new(BattleTaskState)
	*p = x
	return p
}

func (x BattleTaskState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BattleTaskState) Descriptor() protoreflect.EnumDescriptor {
	return file_com_battle_enum_proto_enumTypes[0].Descriptor()
}

func (BattleTaskState) Type() protoreflect.EnumType {
	return &file_com_battle_enum_proto_enumTypes[0]
}

func (x BattleTaskState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *BattleTaskState) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = BattleTaskState(num)
	return nil
}

// Deprecated: Use BattleTaskState.Descriptor instead.
func (BattleTaskState) EnumDescriptor() ([]byte, []int) {
	return file_com_battle_enum_proto_rawDescGZIP(), []int{0}
}

type PlayerBattleState int32

const (
	PlayerBattleState_PLAYER_BATTLE_STATE_IDLE            PlayerBattleState = 0
	PlayerBattleState_PLAYER_BATTLE_STATE_IN_BATTLE       PlayerBattleState = 1
	PlayerBattleState_PLAYER_BATTLE_STATE_SETTLE          PlayerBattleState = 2
	PlayerBattleState_PLAYER_BATTLE_STATE_OBSERVING       PlayerBattleState = 3
	PlayerBattleState_PLAYER_BATTLE_STATE_OBSERVER_SETTLE PlayerBattleState = 4
)

// Enum value maps for PlayerBattleState.
var (
	PlayerBattleState_name = map[int32]string{
		0: "PLAYER_BATTLE_STATE_IDLE",
		1: "PLAYER_BATTLE_STATE_IN_BATTLE",
		2: "PLAYER_BATTLE_STATE_SETTLE",
		3: "PLAYER_BATTLE_STATE_OBSERVING",
		4: "PLAYER_BATTLE_STATE_OBSERVER_SETTLE",
	}
	PlayerBattleState_value = map[string]int32{
		"PLAYER_BATTLE_STATE_IDLE":            0,
		"PLAYER_BATTLE_STATE_IN_BATTLE":       1,
		"PLAYER_BATTLE_STATE_SETTLE":          2,
		"PLAYER_BATTLE_STATE_OBSERVING":       3,
		"PLAYER_BATTLE_STATE_OBSERVER_SETTLE": 4,
	}
)

func (x PlayerBattleState) Enum() *PlayerBattleState {
	p := new(PlayerBattleState)
	*p = x
	return p
}

func (x PlayerBattleState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerBattleState) Descriptor() protoreflect.EnumDescriptor {
	return file_com_battle_enum_proto_enumTypes[1].Descriptor()
}

func (PlayerBattleState) Type() protoreflect.EnumType {
	return &file_com_battle_enum_proto_enumTypes[1]
}

func (x PlayerBattleState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *PlayerBattleState) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = PlayerBattleState(num)
	return nil
}

// Deprecated: Use PlayerBattleState.Descriptor instead.
func (PlayerBattleState) EnumDescriptor() ([]byte, []int) {
	return file_com_battle_enum_proto_rawDescGZIP(), []int{1}
}

type BattlerAction int32

const (
	BattlerAction_BATTLER_ACTION_NONE         BattlerAction = 0
	BattlerAction_BATTLER_ACTION_SHIELD_BREAK BattlerAction = 1
	BattlerAction_BATTLER_ACTION_CHANGE_PET   BattlerAction = 2
)

// Enum value maps for BattlerAction.
var (
	BattlerAction_name = map[int32]string{
		0: "BATTLER_ACTION_NONE",
		1: "BATTLER_ACTION_SHIELD_BREAK",
		2: "BATTLER_ACTION_CHANGE_PET",
	}
	BattlerAction_value = map[string]int32{
		"BATTLER_ACTION_NONE":         0,
		"BATTLER_ACTION_SHIELD_BREAK": 1,
		"BATTLER_ACTION_CHANGE_PET":   2,
	}
)

func (x BattlerAction) Enum() *BattlerAction {
	p := new(BattlerAction)
	*p = x
	return p
}

func (x BattlerAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BattlerAction) Descriptor() protoreflect.EnumDescriptor {
	return file_com_battle_enum_proto_enumTypes[2].Descriptor()
}

func (BattlerAction) Type() protoreflect.EnumType {
	return &file_com_battle_enum_proto_enumTypes[2]
}

func (x BattlerAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *BattlerAction) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = BattlerAction(num)
	return nil
}

// Deprecated: Use BattlerAction.Descriptor instead.
func (BattlerAction) EnumDescriptor() ([]byte, []int) {
	return file_com_battle_enum_proto_rawDescGZIP(), []int{2}
}

type BoxType int32

const (
	BoxType_BOX_TYPE_INVALID BoxType = 0
	BoxType_BOX_TYPE_COPPER  BoxType = 1
	BoxType_BOX_TYPE_SILVER  BoxType = 2
	BoxType_BOX_TYPE_GOLD    BoxType = 3
)

// Enum value maps for BoxType.
var (
	BoxType_name = map[int32]string{
		0: "BOX_TYPE_INVALID",
		1: "BOX_TYPE_COPPER",
		2: "BOX_TYPE_SILVER",
		3: "BOX_TYPE_GOLD",
	}
	BoxType_value = map[string]int32{
		"BOX_TYPE_INVALID": 0,
		"BOX_TYPE_COPPER":  1,
		"BOX_TYPE_SILVER":  2,
		"BOX_TYPE_GOLD":    3,
	}
)

func (x BoxType) Enum() *BoxType {
	p := new(BoxType)
	*p = x
	return p
}

func (x BoxType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BoxType) Descriptor() protoreflect.EnumDescriptor {
	return file_com_battle_enum_proto_enumTypes[3].Descriptor()
}

func (BoxType) Type() protoreflect.EnumType {
	return &file_com_battle_enum_proto_enumTypes[3]
}

func (x BoxType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *BoxType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = BoxType(num)
	return nil
}

// Deprecated: Use BoxType.Descriptor instead.
func (BoxType) EnumDescriptor() ([]byte, []int) {
	return file_com_battle_enum_proto_rawDescGZIP(), []int{3}
}

type PetRarityType int32

const (
	PetRarityType_PET_RARITY_TYPE_INVALID     PetRarityType = 0
	PetRarityType_PET_RARITY_TYPE_BP          PetRarityType = 1
	PetRarityType_PET_RARITY_TYPE_SEASON_RARE PetRarityType = 2
	PetRarityType_PET_RARITY_TYPE_SEASON      PetRarityType = 3
	PetRarityType_PET_RARITY_TYPE_RARE        PetRarityType = 4
	PetRarityType_PET_RARITY_TYPE_COMMON      PetRarityType = 5
)

// Enum value maps for PetRarityType.
var (
	PetRarityType_name = map[int32]string{
		0: "PET_RARITY_TYPE_INVALID",
		1: "PET_RARITY_TYPE_BP",
		2: "PET_RARITY_TYPE_SEASON_RARE",
		3: "PET_RARITY_TYPE_SEASON",
		4: "PET_RARITY_TYPE_RARE",
		5: "PET_RARITY_TYPE_COMMON",
	}
	PetRarityType_value = map[string]int32{
		"PET_RARITY_TYPE_INVALID":     0,
		"PET_RARITY_TYPE_BP":          1,
		"PET_RARITY_TYPE_SEASON_RARE": 2,
		"PET_RARITY_TYPE_SEASON":      3,
		"PET_RARITY_TYPE_RARE":        4,
		"PET_RARITY_TYPE_COMMON":      5,
	}
)

func (x PetRarityType) Enum() *PetRarityType {
	p := new(PetRarityType)
	*p = x
	return p
}

func (x PetRarityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PetRarityType) Descriptor() protoreflect.EnumDescriptor {
	return file_com_battle_enum_proto_enumTypes[4].Descriptor()
}

func (PetRarityType) Type() protoreflect.EnumType {
	return &file_com_battle_enum_proto_enumTypes[4]
}

func (x PetRarityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *PetRarityType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = PetRarityType(num)
	return nil
}

// Deprecated: Use PetRarityType.Descriptor instead.
func (PetRarityType) EnumDescriptor() ([]byte, []int) {
	return file_com_battle_enum_proto_rawDescGZIP(), []int{4}
}

type PetMutationType int32

const (
	PetMutationType_PET_MUTATION_TYPE_INVALID   PetMutationType = 0
	PetMutationType_PET_MUTATION_TYPE_NIGHTMARE PetMutationType = 1
	PetMutationType_PET_MUTATION_TYPE_SHINY     PetMutationType = 2
	PetMutationType_PET_MUTATION_TYPE_FANTASTIC PetMutationType = 3
	PetMutationType_PET_MUTATION_TYPE_HYBRID    PetMutationType = 4
	PetMutationType_PET_MUTATION_TYPE_COMMON    PetMutationType = 5
)

// Enum value maps for PetMutationType.
var (
	PetMutationType_name = map[int32]string{
		0: "PET_MUTATION_TYPE_INVALID",
		1: "PET_MUTATION_TYPE_NIGHTMARE",
		2: "PET_MUTATION_TYPE_SHINY",
		3: "PET_MUTATION_TYPE_FANTASTIC",
		4: "PET_MUTATION_TYPE_HYBRID",
		5: "PET_MUTATION_TYPE_COMMON",
	}
	PetMutationType_value = map[string]int32{
		"PET_MUTATION_TYPE_INVALID":   0,
		"PET_MUTATION_TYPE_NIGHTMARE": 1,
		"PET_MUTATION_TYPE_SHINY":     2,
		"PET_MUTATION_TYPE_FANTASTIC": 3,
		"PET_MUTATION_TYPE_HYBRID":    4,
		"PET_MUTATION_TYPE_COMMON":    5,
	}
)

func (x PetMutationType) Enum() *PetMutationType {
	p := new(PetMutationType)
	*p = x
	return p
}

func (x PetMutationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PetMutationType) Descriptor() protoreflect.EnumDescriptor {
	return file_com_battle_enum_proto_enumTypes[5].Descriptor()
}

func (PetMutationType) Type() protoreflect.EnumType {
	return &file_com_battle_enum_proto_enumTypes[5]
}

func (x PetMutationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *PetMutationType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = PetMutationType(num)
	return nil
}

// Deprecated: Use PetMutationType.Descriptor instead.
func (PetMutationType) EnumDescriptor() ([]byte, []int) {
	return file_com_battle_enum_proto_rawDescGZIP(), []int{5}
}

type PetAttrType int32

const (
	PetAttrType_PET_ATTR_TYPE_INVALID PetAttrType = 0
	PetAttrType_PET_ATTR_TYPE_HP      PetAttrType = 1
	PetAttrType_PET_ATTR_TYPE_PHY_ATK PetAttrType = 2
	PetAttrType_PET_ATTR_TYPE_SPE_ATK PetAttrType = 3
	PetAttrType_PET_ATTR_TYPE_PHY_DEF PetAttrType = 4
	PetAttrType_PET_ATTR_TYPE_SPE_DEF PetAttrType = 5
	PetAttrType_PET_ATTR_TYPE_SPEED   PetAttrType = 6
)

// Enum value maps for PetAttrType.
var (
	PetAttrType_name = map[int32]string{
		0: "PET_ATTR_TYPE_INVALID",
		1: "PET_ATTR_TYPE_HP",
		2: "PET_ATTR_TYPE_PHY_ATK",
		3: "PET_ATTR_TYPE_SPE_ATK",
		4: "PET_ATTR_TYPE_PHY_DEF",
		5: "PET_ATTR_TYPE_SPE_DEF",
		6: "PET_ATTR_TYPE_SPEED",
	}
	PetAttrType_value = map[string]int32{
		"PET_ATTR_TYPE_INVALID": 0,
		"PET_ATTR_TYPE_HP":      1,
		"PET_ATTR_TYPE_PHY_ATK": 2,
		"PET_ATTR_TYPE_SPE_ATK": 3,
		"PET_ATTR_TYPE_PHY_DEF": 4,
		"PET_ATTR_TYPE_SPE_DEF": 5,
		"PET_ATTR_TYPE_SPEED":   6,
	}
)

func (x PetAttrType) Enum() *PetAttrType {
	p := new(PetAttrType)
	*p = x
	return p
}

func (x PetAttrType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PetAttrType) Descriptor() protoreflect.EnumDescriptor {
	return file_com_battle_enum_proto_enumTypes[6].Descriptor()
}

func (PetAttrType) Type() protoreflect.EnumType {
	return &file_com_battle_enum_proto_enumTypes[6]
}

func (x PetAttrType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *PetAttrType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = PetAttrType(num)
	return nil
}

// Deprecated: Use PetAttrType.Descriptor instead.
func (PetAttrType) EnumDescriptor() ([]byte, []int) {
	return file_com_battle_enum_proto_rawDescGZIP(), []int{6}
}

var File_com_battle_enum_proto protoreflect.FileDescriptor

const file_com_battle_enum_proto_rawDesc = "" +
	"\n" +
	"\x15com_battle_enum.proto\x12\x04Next*@\n" +
	"\x0fBattleTaskState\x12\x0e\n" +
	"\n" +
	"BTS_UNKNOW\x10\x00\x12\x0f\n" +
	"\vBTS_SUCCESS\x10\x01\x12\f\n" +
	"\bBTS_FAIL\x10\x02*\xc0\x01\n" +
	"\x11PlayerBattleState\x12\x1c\n" +
	"\x18PLAYER_BATTLE_STATE_IDLE\x10\x00\x12!\n" +
	"\x1dPLAYER_BATTLE_STATE_IN_BATTLE\x10\x01\x12\x1e\n" +
	"\x1aPLAYER_BATTLE_STATE_SETTLE\x10\x02\x12!\n" +
	"\x1dPLAYER_BATTLE_STATE_OBSERVING\x10\x03\x12'\n" +
	"#PLAYER_BATTLE_STATE_OBSERVER_SETTLE\x10\x04*h\n" +
	"\rBattlerAction\x12\x17\n" +
	"\x13BATTLER_ACTION_NONE\x10\x00\x12\x1f\n" +
	"\x1bBATTLER_ACTION_SHIELD_BREAK\x10\x01\x12\x1d\n" +
	"\x19BATTLER_ACTION_CHANGE_PET\x10\x02*\\\n" +
	"\aBoxType\x12\x14\n" +
	"\x10BOX_TYPE_INVALID\x10\x00\x12\x13\n" +
	"\x0fBOX_TYPE_COPPER\x10\x01\x12\x13\n" +
	"\x0fBOX_TYPE_SILVER\x10\x02\x12\x11\n" +
	"\rBOX_TYPE_GOLD\x10\x03*\xb7\x01\n" +
	"\rPetRarityType\x12\x1b\n" +
	"\x17PET_RARITY_TYPE_INVALID\x10\x00\x12\x16\n" +
	"\x12PET_RARITY_TYPE_BP\x10\x01\x12\x1f\n" +
	"\x1bPET_RARITY_TYPE_SEASON_RARE\x10\x02\x12\x1a\n" +
	"\x16PET_RARITY_TYPE_SEASON\x10\x03\x12\x18\n" +
	"\x14PET_RARITY_TYPE_RARE\x10\x04\x12\x1a\n" +
	"\x16PET_RARITY_TYPE_COMMON\x10\x05*\xcb\x01\n" +
	"\x0fPetMutationType\x12\x1d\n" +
	"\x19PET_MUTATION_TYPE_INVALID\x10\x00\x12\x1f\n" +
	"\x1bPET_MUTATION_TYPE_NIGHTMARE\x10\x01\x12\x1b\n" +
	"\x17PET_MUTATION_TYPE_SHINY\x10\x02\x12\x1f\n" +
	"\x1bPET_MUTATION_TYPE_FANTASTIC\x10\x03\x12\x1c\n" +
	"\x18PET_MUTATION_TYPE_HYBRID\x10\x04\x12\x1c\n" +
	"\x18PET_MUTATION_TYPE_COMMON\x10\x05*\xc3\x01\n" +
	"\vPetAttrType\x12\x19\n" +
	"\x15PET_ATTR_TYPE_INVALID\x10\x00\x12\x14\n" +
	"\x10PET_ATTR_TYPE_HP\x10\x01\x12\x19\n" +
	"\x15PET_ATTR_TYPE_PHY_ATK\x10\x02\x12\x19\n" +
	"\x15PET_ATTR_TYPE_SPE_ATK\x10\x03\x12\x19\n" +
	"\x15PET_ATTR_TYPE_PHY_DEF\x10\x04\x12\x19\n" +
	"\x15PET_ATTR_TYPE_SPE_DEF\x10\x05\x12\x17\n" +
	"\x13PET_ATTR_TYPE_SPEED\x10\x06"

var (
	file_com_battle_enum_proto_rawDescOnce sync.Once
	file_com_battle_enum_proto_rawDescData []byte
)

func file_com_battle_enum_proto_rawDescGZIP() []byte {
	file_com_battle_enum_proto_rawDescOnce.Do(func() {
		file_com_battle_enum_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_com_battle_enum_proto_rawDesc), len(file_com_battle_enum_proto_rawDesc)))
	})
	return file_com_battle_enum_proto_rawDescData
}

var file_com_battle_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_com_battle_enum_proto_goTypes = []any{
	(BattleTaskState)(0),   // 0: Next.BattleTaskState
	(PlayerBattleState)(0), // 1: Next.PlayerBattleState
	(BattlerAction)(0),     // 2: Next.BattlerAction
	(BoxType)(0),           // 3: Next.BoxType
	(PetRarityType)(0),     // 4: Next.PetRarityType
	(PetMutationType)(0),   // 5: Next.PetMutationType
	(PetAttrType)(0),       // 6: Next.PetAttrType
}
var file_com_battle_enum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_com_battle_enum_proto_init() }
func file_com_battle_enum_proto_init() {
	if File_com_battle_enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_com_battle_enum_proto_rawDesc), len(file_com_battle_enum_proto_rawDesc)),
			NumEnums:      7,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_com_battle_enum_proto_goTypes,
		DependencyIndexes: file_com_battle_enum_proto_depIdxs,
		EnumInfos:         file_com_battle_enum_proto_enumTypes,
	}.Build()
	File_com_battle_enum_proto = out.File
	file_com_battle_enum_proto_goTypes = nil
	file_com_battle_enum_proto_depIdxs = nil
}
